const PHONES = [
  {
    "id": "samsung-galaxy-s24-ultra",
    "name": "Samsung Galaxy S24 Ultra",
    "brand": "Samsung",
    "released": "2024-01-24",
    "status": "Tersedia",
    "priceIDR": 21999000,
    "priceUSD": 1299,
    "rating": 4.8,
    "reviewCount": 2314,
    "hits": 5840201,
    "antutu": 1745852,
    "colors": ["Titanium Black", "Titanium Gray", "Titanium Violet", "Titanium Yellow"],
    "colorHex": ["#2b2b2e", "#8a8d91", "#b9a7c9", "#e8d48b"],
    "network": { "teknologi": "GSM / CDMA / HSPA / EVDO / LTE / 5G", "sim": "Nano-SIM + eSIM / Dual Nano-SIM", "dukungan5G": true },
    "launch": { "diumumkan": "17 Jan 2024", "rilis": "24 Jan 2024", "status": "Tersedia" },
    "body": { "dimensi": "162.3 x 79 x 8.6 mm", "berat": "232 g", "material": "Titanium frame, Gorilla Armor depan, kaca belakang", "simDetail": "Dual SIM (Nano + eSIM)", "tahanAir": "IP68 (1.5m, 30 mnt)", "tambahan": "S Pen built-in, latency 2.8ms" },
    "display": { "tipe": "Dynamic AMOLED 2X, 120Hz, HDR10+", "ukuran": "6.8 inci", "resolusi": "1440 x 3120 piksel, 505 ppi", "kecerahan": "2600 nits (peak)", "proteksi": "Corning Gorilla Armor", "refreshRate": 120, "sizeInch": 6.8 },
    "platform": { "os": "Android 14, One UI 6.1 (upgrade s/d Android 21)", "chipset": "Snapdragon 8 Gen 3 (4 nm)", "cpu": "Octa-core (1x3.39GHz + 3x3.1GHz + 2x2.9GHz + 2x2.2GHz)", "gpu": "Adreno 750" },
    "memory": { "slotKartu": "Tidak", "ram": [8, 12], "ramUtama": 12, "internal": [256, 512, 1024], "storageUtama": 256, "tipe": "UFS 4.0" },
    "mainCamera": { "konfigurasi": "200MP wide + 12MP ultrawide + 10MP tele 3x + 50MP periskop 5x", "detail": "200 MP, f/1.7, 24mm (wide), OIS | 12 MP, f/2.2, 13mm (ultrawide) | 10 MP, f/2.4, 67mm (tele 3x) | 50 MP, f/3.4, 111mm (periskop 5x)", "fitur": "Laser AF, OIS, zoom optik 5x, zoom digital 100x, Super Steady", "video": "8K@24fps, 4K@30/60/120fps, 1080p@240fps, HDR10+" },
    "selfieCamera": { "resolusi": "12 MP, f/2.2, 26mm (wide)", "fitur": "Dual Pixel PDAF, HDR", "video": "4K@30/60fps" },
    "sound": { "pengeras": "Stereo (AKG), Dolby Atmos", "jack": "Tidak ada", "tambahan": "Audio 32-bit/384kHz" },
    "comms": { "wifi": "Wi-Fi 802.11 a/b/g/n/ac/6e/7, tri-band, Wi-Fi Direct", "bluetooth": "5.3, A2DP, LE", "nfc": true, "infrared": false, "usb": "USB-C 3.2, OTG, DisplayPort 1.2", "gps": "GPS, GLONASS, BDS, GALILEO, QZSS", "uwb": true },
    "sensors": ["Fingerprint ultrasonik di layar", "Accelerometer", "Gyro", "Proximity", "Kompas", "Barometer"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Ion 5000 mAh", "charging": "45W kabel (65% dalam 30 mnt), 15W wireless, 4.5W reverse", "wireless": true },
    "prices": [
      { "toko": "Samsung Official Store", "harga": 21999000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Erafone", "harga": 21499000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Rp 18.000", "garansi": "Resmi 1 tahun" },
      { "toko": "Tokopedia - GadgetHub", "harga": 20750000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Shopee - CellWorld", "harga": 20499000, "stok": "2 unit", "ratingToko": 4.6, "ongkir": "Gratis", "garansi": "Distributor 1 tahun" }
    ],
    "pros": ["Kamera 200MP terbaik di kelasnya dengan zoom 5x tajam", "Snapdragon 8 Gen 3 sangat kencang dan efisien", "S Pen bawaan produktif", "Update 7 tahun"],
    "cons": ["Harga tinggi", "Pengisian 45W kalah dari rival China", "Bodi besar dan berat"]
  },
  {
    "id": "iphone-15-pro-max",
    "name": "Apple iPhone 15 Pro Max",
    "brand": "Apple",
    "released": "2023-09-22",
    "status": "Tersedia",
    "priceIDR": 24999000,
    "priceUSD": 1199,
    "rating": 4.9,
    "reviewCount": 3102,
    "hits": 6120450,
    "antutu": 1642280,
    "colors": ["Natural Titanium", "Blue Titanium", "White Titanium", "Black Titanium"],
    "colorHex": ["#c2b8a3", "#3b4453", "#e3e4e6", "#1c1c1e"],
    "network": { "teknologi": "GSM / CDMA / HSPA / EVDO / LTE / 5G", "sim": "Nano-SIM + eSIM / Dual eSIM", "dukungan5G": true },
    "launch": { "diumumkan": "12 Sep 2023", "rilis": "22 Sep 2023", "status": "Tersedia" },
    "body": { "dimensi": "159.9 x 76.7 x 8.3 mm", "berat": "221 g", "material": "Titanium frame, Ceramic Shield depan", "simDetail": "Dual eSIM / Nano-SIM + eSIM", "tahanAir": "IP68 (6m, 30 mnt)", "tambahan": "Action Button, USB-C" },
    "display": { "tipe": "LTPO Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision", "ukuran": "6.7 inci", "resolusi": "1290 x 2796 piksel, 460 ppi", "kecerahan": "2000 nits (peak outdoor)", "proteksi": "Ceramic Shield", "refreshRate": 120, "sizeInch": 6.7 },
    "platform": { "os": "iOS 17 (upgrade ke iOS 18)", "chipset": "Apple A17 Pro (3 nm)", "cpu": "Hexa-core (2x3.78GHz + 4x2.11GHz)", "gpu": "Apple GPU 6-core, ray tracing" },
    "memory": { "slotKartu": "Tidak", "ram": [8], "ramUtama": 8, "internal": [256, 512, 1024], "storageUtama": 256, "tipe": "NVMe" },
    "mainCamera": { "konfigurasi": "48MP wide + 12MP ultrawide + 12MP periskop 5x", "detail": "48 MP, f/1.8, 24mm (wide), sensor-shift OIS | 12 MP, f/2.2 (ultrawide) | 12 MP, f/2.8, 120mm (periskop 5x)", "fitur": "LiDAR, Photonic Engine, ProRAW, Night mode", "video": "4K@24/30/60fps, ProRes, Log, ACES" },
    "selfieCamera": { "resolusi": "12 MP, f/1.9, 23mm + SL 3D", "fitur": "Face ID, HDR, Cinematic mode", "video": "4K@30/60fps" },
    "sound": { "pengeras": "Stereo, Dolby Atmos, Spatial Audio", "jack": "Tidak ada", "tambahan": "Audio Zoom" },
    "comms": { "wifi": "Wi-Fi 6E, tri-band", "bluetooth": "5.3", "nfc": true, "infrared": false, "usb": "USB-C 3.2 Gen 2, DisplayPort", "gps": "GPS presisi ganda, GLONASS, GALILEO, QZSS, BeiDou", "uwb": true },
    "sensors": ["Face ID", "LiDAR Scanner", "Accelerometer", "Gyro", "Proximity", "Kompas", "Barometer"],
    "battery": { "kapasitas": 4422, "tipe": "Li-Ion 4422 mAh", "charging": "27W kabel (50% 30 mnt, PD2.0), 15W MagSafe/Qi2", "wireless": true },
    "prices": [
      { "toko": "iBox Official", "harga": 24999000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi Apple 1 tahun" },
      { "toko": "Digimap", "harga": 24499000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi Apple 1 tahun" },
      { "toko": "Tokopedia - iStyle", "harga": 23750000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Resmi Apple 1 tahun" }
    ],
    "pros": ["Chip A17 Pro terkencang dengan ray tracing", "Material titanium ringan dan premium", "Kamera ProRes untuk videografer", "USB-C 3.2 cepat"],
    "cons": ["Harga paling mahal", "Pengisian lambat 27W", "Tidak ada Touch ID"]
  },
  {
    "id": "xiaomi-redmi-note-13-pro",
    "name": "Xiaomi Redmi Note 13 Pro 5G",
    "brand": "Xiaomi",
    "released": "2024-01-15",
    "status": "Tersedia",
    "priceIDR": 4299000,
    "priceUSD": 299,
    "rating": 4.6,
    "reviewCount": 5871,
    "hits": 4210330,
    "antutu": 608761,
    "colors": ["Midnight Black", "Ocean Teals", "Lavender Purple"],
    "colorHex": ["#15161a", "#2e6f73", "#b9a7d6"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM", "dukungan5G": true },
    "launch": { "diumumkan": "04 Jan 2024", "rilis": "15 Jan 2024", "status": "Tersedia" },
    "body": { "dimensi": "161.1 x 74.9 x 7.98 mm", "berat": "187 g", "material": "Gorilla Glass Victus depan, plastik belakang", "simDetail": "Dual Nano-SIM", "tahanAir": "IP54", "tambahan": "IR Blaster, jack 3.5mm" },
    "display": { "tipe": "AMOLED CrystalRes, 120Hz, HDR10+, Dolby Vision", "ukuran": "6.67 inci", "resolusi": "1220 x 2712 piksel, 446 ppi", "kecerahan": "1800 nits (peak)", "proteksi": "Gorilla Glass Victus", "refreshRate": 120, "sizeInch": 6.67 },
    "platform": { "os": "MIUI 14 berbasis Android 13 (upgrade HyperOS)", "chipset": "Snapdragon 7s Gen 2 (4 nm)", "cpu": "Octa-core (4x2.40GHz + 4x1.95GHz)", "gpu": "Adreno 710" },
    "memory": { "slotKartu": "Tidak", "ram": [8, 12], "ramUtama": 8, "internal": [256, 512], "storageUtama": 256, "tipe": "UFS 2.2" },
    "mainCamera": { "konfigurasi": "200MP wide + 8MP ultrawide + 2MP macro", "detail": "200 MP, f/1.7, OIS | 8 MP, f/2.2 ultrawide | 2 MP macro", "fitur": "OIS, Night mode, 4x lossless zoom sensor", "video": "4K@30fps, 1080p@30/60fps, gyro-EIS" },
    "selfieCamera": { "resolusi": "16 MP, f/2.4", "fitur": "HDR, beautify", "video": "1080p@30/60fps" },
    "sound": { "pengeras": "Stereo ganda, Dolby Atmos", "jack": "Ada, 3.5mm", "tambahan": "Hi-Res Audio" },
    "comms": { "wifi": "Wi-Fi ac, dual-band", "bluetooth": "5.2", "nfc": true, "infrared": true, "usb": "USB-C 2.0, OTG", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5100, "tipe": "Li-Po 5100 mAh", "charging": "67W turbo (100% 44 mnt)", "wireless": false },
    "prices": [
      { "toko": "Xiaomi Official Store", "harga": 4299000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Erafone", "harga": 4199000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Rp 12.000", "garansi": "Resmi 1 tahun" },
      { "toko": "Shopee - Mi Store", "harga": 3999000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Tokopedia - Fonel", "harga": 3899000, "stok": "5 unit", "ratingToko": 4.6, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Layar AMOLED 1.5K flagship di harga mid-range", "Kamera 200MP OIS", "Charging 67W cepat", "Ada jack 3.5mm dan IR blaster"],
    "cons": ["Chipset 7s Gen 2 bukan untuk gaming berat", "Storage UFS 2.2", "Tahan air hanya IP54"]
  },
  {
    "id": "oppo-reno-11-pro",
    "name": "Oppo Reno 11 Pro 5G",
    "brand": "Oppo",
    "released": "2024-01-20",
    "status": "Tersedia",
    "priceIDR": 8999000,
    "priceUSD": 549,
    "rating": 4.5,
    "reviewCount": 1290,
    "hits": 1874220,
    "antutu": 868000,
    "colors": ["Pearl White", "Rock Grey"],
    "colorHex": ["#ece7dd", "#4a4d52"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM", "dukungan5G": true },
    "launch": { "diumumkan": "10 Jan 2024", "rilis": "20 Jan 2024", "status": "Tersedia" },
    "body": { "dimensi": "162.4 x 74.1 x 7.6 mm", "berat": "190 g", "material": "Kaca depan-belakang, frame plastik", "simDetail": "Dual Nano-SIM", "tahanAir": "IP54", "tambahan": "IR Blaster" },
    "display": { "tipe": "AMOLED 120Hz, HDR10+", "ukuran": "6.7 inci", "resolusi": "1080 x 2412 piksel, 394 ppi", "kecerahan": "1600 nits (peak)", "proteksi": "Asahi Glass AGC DT-Star2", "refreshRate": 120, "sizeInch": 6.7 },
    "platform": { "os": "ColorOS 14 berbasis Android 14", "chipset": "Dimensity 8200 (4 nm)", "cpu": "Octa-core (1x3.1GHz + 3x3.0GHz + 4x2.0GHz)", "gpu": "Mali-G610 MC6" },
    "memory": { "slotKartu": "Tidak", "ram": [12], "ramUtama": 12, "internal": [512], "storageUtama": 512, "tipe": "UFS 3.1" },
    "mainCamera": { "konfigurasi": "50MP wide OIS + 32MP tele 2x + 8MP ultrawide (Hasselblad tuned)", "detail": "50 MP Sony IMX890, f/1.8, OIS | 32 MP IMX709 tele 2x | 8 MP ultrawide", "fitur": "Hasselblad Portrait, OIS, 2x optical", "video": "4K@30/60fps, gyro-EIS" },
    "selfieCamera": { "resolusi": "32 MP, f/2.4, AF", "fitur": "Portrait, HDR", "video": "4K@30fps" },
    "sound": { "pengeras": "Stereo, Dolby Atmos", "jack": "Tidak ada", "tambahan": "Hi-Res" },
    "comms": { "wifi": "Wi-Fi 6, dual-band", "bluetooth": "5.3", "nfc": true, "infrared": true, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 4600, "tipe": "Li-Po 4600 mAh", "charging": "80W SuperVOOC (100% 30 mnt), reverse wired", "wireless": false },
    "prices": [
      { "toko": "Oppo Official Store", "harga": 8999000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Erafone", "harga": 8799000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Tokopedia - Oppo Gallery", "harga": 8499000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Kamera portrait Hasselblad sangat natural", "Desain tipis ringan premium", "Charging 80W sangat cepat", "Selfie 32MP AF tajam"],
    "cons": ["Baterai 4600 mAh tergolong kecil", "Tidak ada ultrawide telefoto panjang", "Harga naik dari pendahulu"]
  },
  {
    "id": "vivo-v30-pro",
    "name": "Vivo V30 Pro 5G",
    "brand": "Vivo",
    "released": "2024-03-05",
    "status": "Tersedia",
    "priceIDR": 8499000,
    "priceUSD": 519,
    "rating": 4.6,
    "reviewCount": 980,
    "hits": 1540890,
    "antutu": 912450,
    "colors": ["Bloom White", "Waving Aqua"],
    "colorHex": ["#f2ede6", "#7fb8b5"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM", "dukungan5G": true },
    "launch": { "diumumkan": "28 Feb 2024", "rilis": "05 Mar 2024", "status": "Tersedia" },
    "body": { "dimensi": "164.4 x 75.1 x 7.5 mm", "berat": "188 g", "material": "Kaca depan-belakang 3D curved", "simDetail": "Dual Nano-SIM", "tahanAir": "IP54", "tambahan": "Aura Light Portrait 3.0" },
    "display": { "tipe": "AMOLED 120Hz, HDR10+", "ukuran": "6.78 inci", "resolusi": "1260 x 2800 piksel, 453 ppi", "kecerahan": "2800 nits (peak)", "proteksi": "Schott Xensation", "refreshRate": 120, "sizeInch": 6.78 },
    "platform": { "os": "Funtouch 14 berbasis Android 14", "chipset": "Dimensity 8200 (4 nm)", "cpu": "Octa-core (1x3.1GHz + 3x3.0GHz + 4x2.0GHz)", "gpu": "Mali-G610 MC6" },
    "memory": { "slotKartu": "Tidak", "ram": [12], "ramUtama": 12, "internal": [512], "storageUtama": 512, "tipe": "UFS 3.1" },
    "mainCamera": { "konfigurasi": "50MP wide ZEISS + 50MP ultrawide + 50MP portrait 2x", "detail": "3x 50MP ZEISS: IMX920 wide OIS +超 wide + IMX816 portrait", "fitur": "ZEISS optics, Aura Light, OIS", "video": "4K@30fps" },
    "selfieCamera": { "resolusi": "50 MP, f/2.0, AF, wide", "fitur": "ZEISS, dual soft LED", "video": "4K@30fps" },
    "sound": { "pengeras": "Mono + stereo virtual", "jack": "Tidak ada", "tambahan": "Hi-Res" },
    "comms": { "wifi": "Wi-Fi ac dual-band", "bluetooth": "5.3", "nfc": true, "infrared": false, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "80W FlashCharge (100% 33 mnt)", "wireless": false },
    "prices": [
      { "toko": "Vivo Official Store", "harga": 8499000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Erafone", "harga": 8299000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Semua kamera 50MP ZEISS, langka di kelasnya", "Layar 2800 nits sangat terang", "Bodi tipis 7.5mm", "Selfie 50MP AF terbaik"],
    "cons": ["Video hanya 4K30, tanpa 60fps", "Speaker belum stereo penuh", "Funtouch banyak bloatware"]
  },
  {
    "id": "samsung-galaxy-a54",
    "name": "Samsung Galaxy A54 5G",
    "brand": "Samsung",
    "released": "2023-03-24",
    "status": "Tersedia",
    "priceIDR": 5999000,
    "priceUSD": 449,
    "rating": 4.5,
    "reviewCount": 4210,
    "hits": 3980110,
    "antutu": 536943,
    "colors": ["Awesome Lime", "Awesome Graphite", "Awesome Violet", "Awesome White"],
    "colorHex": ["#b8d94e", "#3a3b3d", "#b9a7d6", "#f2f2f2"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Single/Dual Nano-SIM + microSD hybrid", "dukungan5G": true },
    "launch": { "diumumkan": "15 Mar 2023", "rilis": "24 Mar 2023", "status": "Tersedia" },
    "body": { "dimensi": "158.2 x 76.7 x 8.2 mm", "berat": "202 g", "material": "Gorilla Glass 5 depan-belakang", "simDetail": "Hybrid Dual SIM + microSD s/d 1TB", "tahanAir": "IP67", "tambahan": "-" },
    "display": { "tipe": "Super AMOLED 120Hz, HDR10+", "ukuran": "6.4 inci", "resolusi": "1080 x 2340 piksel, 403 ppi", "kecerahan": "1000 nits (HBM)", "proteksi": "Gorilla Glass 5", "refreshRate": 120, "sizeInch": 6.4 },
    "platform": { "os": "One UI 5.1 Android 13 (upgrade ke Android 17)", "chipset": "Exynos 1380 (5 nm)", "cpu": "Octa-core (4x2.4GHz + 4x2.0GHz)", "gpu": "Mali-G68 MP5" },
    "memory": { "slotKartu": "Ya, hybrid microSD s/d 1TB", "ram": [6, 8], "ramUtama": 8, "internal": [128, 256], "storageUtama": 256, "tipe": "UFS 2.2" },
    "mainCamera": { "konfigurasi": "50MP wide OIS + 12MP ultrawide + 5MP macro", "detail": "50 MP, f/1.8, OIS | 12 MP ultrawide | 5 MP macro", "fitur": "OIS, Nightography, VDIS", "video": "4K@30fps, gyro-EIS" },
    "selfieCamera": { "resolusi": "32 MP, f/2.2", "fitur": "HDR", "video": "4K@30fps" },
    "sound": { "pengeras": "Stereo, Dolby Atmos", "jack": "Tidak ada", "tambahan": "-" },
    "comms": { "wifi": "Wi-Fi 6, dual-band, Wi-Fi Direct", "bluetooth": "5.3", "nfc": true, "infrared": false, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "25W (50% 30 mnt)", "wireless": false },
    "prices": [
      { "toko": "Samsung Official Store", "harga": 5999000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Tokopedia - Terlaris", "harga": 5299000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Shopee - Star Seller", "harga": 5199000, "stok": "Ready", "ratingToko": 4.6, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["IP67 + Gorilla Glass 5 kokoh", "Ada slot microSD", "Update 4+5 tahun", "Kamera OIS stabil"],
    "cons": ["Charging hanya 25W", "Exynos 1380 panas saat gaming", "Bezel agak tebal"]
  },
  {
    "id": "poco-x6-pro",
    "name": "POCO X6 Pro 5G",
    "brand": "Xiaomi",
    "released": "2024-01-25",
    "status": "Tersedia",
    "priceIDR": 4799000,
    "priceUSD": 329,
    "rating": 4.7,
    "reviewCount": 3450,
    "hits": 2876540,
    "antutu": 1410000,
    "colors": ["Black", "Yellow", "Grey"],
    "colorHex": ["#1b1b1d", "#e8c832", "#6b6e73"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM", "dukungan5G": true },
    "launch": { "diumumkan": "11 Jan 2024", "rilis": "25 Jan 2024", "status": "Tersedia" },
    "body": { "dimensi": "160.5 x 74.3 x 8.3 mm", "berat": "190 g", "material": "Plastik vegan leather (varian kuning)", "simDetail": "Dual Nano-SIM", "tahanAir": "IP54", "tambahan": "IR Blaster" },
    "display": { "tipe": "AMOLED CrystalRes 120Hz, Dolby Vision, 68B warna", "ukuran": "6.67 inci", "resolusi": "1220 x 2712 piksel", "kecerahan": "1800 nits peak", "proteksi": "Gorilla Glass 5", "refreshRate": 120, "sizeInch": 6.67 },
    "platform": { "os": "HyperOS berbasis Android 14", "chipset": "Dimensity 8300 Ultra (4 nm)", "cpu": "Octa-core (1x3.35GHz + 3x3.0GHz + 4x2.2GHz)", "gpu": "Mali-G615 MC6" },
    "memory": { "slotKartu": "Tidak", "ram": [8, 12], "ramUtama": 12, "internal": [256, 512], "storageUtama": 512, "tipe": "UFS 4.0" },
    "mainCamera": { "konfigurasi": "64MP wide OIS + 8MP ultrawide + 2MP macro", "detail": "64 MP Omnivision OV64B, f/1.7, OIS", "fitur": "OIS, Night mode", "video": "4K@30fps" },
    "selfieCamera": { "resolusi": "16 MP", "fitur": "HDR", "video": "1080p@30fps" },
    "sound": { "pengeras": "Stereo, Dolby Atmos", "jack": "Tidak ada", "tambahan": "Hi-Res" },
    "comms": { "wifi": "Wi-Fi 6", "bluetooth": "5.4", "nfc": true, "infrared": true, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "67W turbo", "wireless": false },
    "prices": [
      { "toko": "POCO Official Store", "harga": 4799000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Shopee - POCO ID", "harga": 4599000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Dimensity 8300 Ultra terkencang di harga 4 jutaan, AnTuTu 1.4 jt", "UFS 4.0 + RAM 12GB", "Layar 1.5K flagship", "Value for money terbaik"],
    "cons": ["Kamera biasa saja", "Bloatware HyperOS", "Material plastik"]
  },
  {
    "id": "realme-11-pro-plus",
    "name": "Realme 11 Pro+ 5G",
    "brand": "Realme",
    "released": "2023-07-18",
    "status": "Tersedia",
    "priceIDR": 6999000,
    "priceUSD": 429,
    "rating": 4.4,
    "reviewCount": 1120,
    "hits": 1320450,
    "antutu": 541402,
    "colors": ["Sunrise Beige", "Oasis Green", "Astral Black"],
    "colorHex": ["#e6d5b8", "#3d5a4c", "#1c1c1e"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM", "dukungan5G": true },
    "launch": { "diumumkan": "10 Mei 2023", "rilis": "18 Jul 2023", "status": "Tersedia" },
    "body": { "dimensi": "161.6 x 73.9 x 8.2 mm", "berat": "183 g", "material": "Vegan leather + kaca curved", "simDetail": "Dual Nano-SIM", "tahanAir": "-", "tambahan": "Desain kolaborasi Matteo Menotto" },
    "display": { "tipe": "AMOLED curved 120Hz, HDR10+", "ukuran": "6.7 inci", "resolusi": "1080 x 2412 piksel", "kecerahan": "950 nits", "proteksi": "Tidak disebutkan", "refreshRate": 120, "sizeInch": 6.7 },
    "platform": { "os": "Realme UI 4.0 Android 13", "chipset": "Dimensity 7050 (6 nm)", "cpu": "Octa-core (2x2.6GHz + 6x2.0GHz)", "gpu": "Mali-G68 MC4" },
    "memory": { "slotKartu": "Tidak", "ram": [12], "ramUtama": 12, "internal": [512], "storageUtama": 512, "tipe": "UFS 3.1" },
    "mainCamera": { "konfigurasi": "200MP Samsung HP3 OIS + 8MP ultrawide + 2MP macro", "detail": "200 MP, f/1.7, OIS, 4x lossless zoom", "fitur": "OIS, Street mode", "video": "4K@30fps" },
    "selfieCamera": { "resolusi": "32 MP Sony IMX615", "fitur": "Portrait", "video": "1080p@30fps" },
    "sound": { "pengeras": "Stereo ganda, Dolby Atmos", "jack": "Tidak ada", "tambahan": "Hi-Res" },
    "comms": { "wifi": "Wi-Fi 6", "bluetooth": "5.2", "nfc": true, "infrared": false, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "100W SuperVOOC (100% 26 mnt)", "wireless": false },
    "prices": [
      { "toko": "Realme Official Store", "harga": 6999000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Erafone", "harga": 6799000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Desain vegan leather premium dan unik", "Charging 100W tercepat di kelasnya", "Kamera 200MP dengan 4x lossless", "Layar curved mewah"],
    "cons": ["Chipset hanya Dimensity 7050", "Tanpa IP rating", "Video selfie mentok 1080p"]
  },
  {
    "id": "infinix-note-40-pro",
    "name": "Infinix Note 40 Pro 5G",
    "brand": "Infinix",
    "released": "2024-04-02",
    "status": "Tersedia",
    "priceIDR": 3499000,
    "priceUSD": 229,
    "rating": 4.5,
    "reviewCount": 2870,
    "hits": 2103400,
    "antutu": 452310,
    "colors": ["Titan Gold", "Obsidian Black"],
    "colorHex": ["#c9a86a", "#1c1c1e"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM", "dukungan5G": true },
    "launch": { "diumumkan": "18 Mar 2024", "rilis": "02 Apr 2024", "status": "Tersedia" },
    "body": { "dimensi": "164.4 x 74.6 x 7.8 mm", "berat": "190 g", "material": "Kaca curved, frame plastik", "simDetail": "Dual Nano-SIM + microSD", "tahanAir": "IP54", "tambahan": "Wireless MagCharge + JBL audio" },
    "display": { "tipe": "AMOLED curved 120Hz", "ukuran": "6.78 inci", "resolusi": "1080 x 2436 piksel", "kecerahan": "1300 nits peak", "proteksi": "Gorilla Glass", "refreshRate": 120, "sizeInch": 6.78 },
    "platform": { "os": "XOS 14 Android 14", "chipset": "Dimensity 7020 (6 nm)", "cpu": "Octa-core (2x2.2GHz + 6x2.0GHz)", "gpu": "IMG BXM-8-256" },
    "memory": { "slotKartu": "Ya, microSD", "ram": [8], "ramUtama": 8, "internal": [256], "storageUtama": 256, "tipe": "UFS 2.2" },
    "mainCamera": { "konfigurasi": "108MP wide OIS + 2MP macro + 2MP depth", "detail": "108 MP, f/1.8, OIS, 3x lossless zoom", "fitur": "OIS, Super Night", "video": "1440p@30fps" },
    "selfieCamera": { "resolusi": "32 MP, f/2.0", "fitur": "Dual LED flash", "video": "1080p@30fps" },
    "sound": { "pengeras": "Stereo JBL, Hi-Res", "jack": "Ada, 3.5mm", "tambahan": "Audio JBL tuned" },
    "comms": { "wifi": "Wi-Fi ac", "bluetooth": "5.2", "nfc": true, "infrared": true, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "70W kabel + 20W wireless MagCharge", "wireless": true },
    "prices": [
      { "toko": "Infinix Official Store", "harga": 3499000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Shopee - Infinix", "harga": 3299000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Satu-satunya 3 jutaan dengan wireless charging 20W", "Layar curved AMOLED", "Speaker JBL stereo", "Kamera 108MP OIS"],
    "cons": ["Chipset Dimensity 7020 pas-pasan", "Update software hanya 2 tahun", "Ultrawide tidak ada"]
  },
  {
    "id": "google-pixel-8-pro",
    "name": "Google Pixel 8 Pro",
    "brand": "Google",
    "released": "2023-10-12",
    "status": "Tersedia",
    "priceIDR": 15999000,
    "priceUSD": 999,
    "rating": 4.7,
    "reviewCount": 860,
    "hits": 1980220,
    "antutu": 1150240,
    "colors": ["Obsidian", "Porcelain", "Bay"],
    "colorHex": ["#1c1c1e", "#e8e0d5", "#a8c7fa"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Nano-SIM + eSIM", "dukungan5G": true },
    "launch": { "diumumkan": "04 Okt 2023", "rilis": "12 Okt 2023", "status": "Tersedia" },
    "body": { "dimensi": "162.6 x 76.5 x 8.8 mm", "berat": "213 g", "material": "Gorilla Glass Victus 2 depan-belakang, aluminium", "simDetail": "Nano-SIM + eSIM", "tahanAir": "IP68", "tambahan": "Sensor suhu" },
    "display": { "tipe": "LTPO OLED Super Actua 120Hz", "ukuran": "6.7 inci", "resolusi": "1344 x 2992 piksel", "kecerahan": "2400 nits peak", "proteksi": "Gorilla Glass Victus 2", "refreshRate": 120, "sizeInch": 6.7 },
    "platform": { "os": "Android 14 (update 7 tahun)", "chipset": "Google Tensor G3 (4 nm)", "cpu": "Nona-core (1x3.0GHz + 4x2.45GHz + 4x2.15GHz)", "gpu": "Immortalis-G715s MC10" },
    "memory": { "slotKartu": "Tidak", "ram": [12], "ramUtama": 12, "internal": [128, 256, 512], "storageUtama": 128, "tipe": "UFS 3.1" },
    "mainCamera": { "konfigurasi": "50MP wide + 48MP ultrawide + 48MP tele 5x", "detail": "50 MP, f/1.7, OIS | 48 MP ultrawide | 48 MP tele 5x OIS", "fitur": "Magic Editor, Best Take, Night Sight, Pro controls", "video": "4K@60fps, 8K upscaling (Video Boost)" },
    "selfieCamera": { "resolusi": "10.5 MP, f/2.2, AF", "fitur": "Auto focus", "video": "4K@30fps" },
    "sound": { "pengeras": "Stereo", "jack": "Tidak ada", "tambahan": "Spatial Audio" },
    "comms": { "wifi": "Wi-Fi 7", "bluetooth": "5.3", "nfc": true, "infrared": false, "usb": "USB-C 3.2", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": true },
    "sensors": ["Fingerprint di layar", "Face Unlock", "Accelerometer", "Gyro", "Proximity", "Kompas", "Barometer", "Termometer"],
    "battery": { "kapasitas": 5050, "tipe": "Li-Po 5050 mAh", "charging": "30W kabel (50% 30 mnt), 23W wireless", "wireless": true },
    "prices": [
      { "toko": "Google Store Partner", "harga": 15999000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Distributor 1 tahun" },
      { "toko": "Tokopedia - PixelID", "harga": 14999000, "stok": "Pre-order", "ratingToko": 4.6, "ongkir": "Gratis", "garansi": "Distributor 1 tahun" }
    ],
    "pros": ["Kamera komputasional terbaik, AI Magic Editor", "Update 7 tahun + Feature Drop", "Layar Super Actua 2400 nits", "Fitur AI Gemini eksklusif"],
    "cons": ["Tensor G3 panas dan kurang efisien", "Charging 30W lambat", "Tidak resmi di Indonesia"]
  },
  {
    "id": "samsung-galaxy-z-flip-5",
    "name": "Samsung Galaxy Z Flip 5",
    "brand": "Samsung",
    "released": "2023-08-11",
    "status": "Tersedia",
    "priceIDR": 15999000,
    "priceUSD": 999,
    "rating": 4.4,
    "reviewCount": 760,
    "hits": 1210890,
    "antutu": 1420500,
    "colors": ["Mint", "Graphite", "Cream", "Lavender"],
    "colorHex": ["#a8d5ba", "#3a3b3d", "#f5f0e1", "#c5b3e6"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Nano-SIM + eSIM", "dukungan5G": true },
    "launch": { "diumumkan": "26 Jul 2023", "rilis": "11 Agu 2023", "status": "Tersedia" },
    "body": { "dimensi": "Lipatan: 85.1 x 71.9 x 15.1 mm / Bentang: 165.1 x 71.9 x 6.9 mm", "berat": "187 g", "material": "Armor Aluminum, Gorilla Glass Victus 2", "simDetail": "Nano-SIM + eSIM", "tahanAir": "IPX8", "tambahan": "Flex Hinge zero-gap, cover screen 3.4 inci" },
    "display": { "tipe": "Foldable Dynamic AMOLED 2X 120Hz + cover 3.4 inci Super AMOLED", "ukuran": "6.7 inci utama", "resolusi": "1080 x 2640 piksel + 720 x 748 cover", "kecerahan": "1750 nits peak", "proteksi": "UTG", "refreshRate": 120, "sizeInch": 6.7 },
    "platform": { "os": "One UI 5.1.1 Android 13", "chipset": "Snapdragon 8 Gen 2 (4 nm)", "cpu": "Octa-core (1x3.36GHz + 2x2.8GHz + 2x2.8GHz + 3x2.0GHz)", "gpu": "Adreno 740" },
    "memory": { "slotKartu": "Tidak", "ram": [8], "ramUtama": 8, "internal": [256, 512], "storageUtama": 256, "tipe": "UFS 4.0" },
    "mainCamera": { "konfigurasi": "12MP wide OIS + 12MP ultrawide", "detail": "12 MP, f/1.8, OIS + 12 MP, f/2.2 ultrawide 123 derajat", "fitur": "FlexCam, auto framing", "video": "4K@60fps" },
    "selfieCamera": { "resolusi": "10 MP, f/2.2", "fitur": "HDR", "video": "4K@30fps" },
    "sound": { "pengeras": "Stereo, Dolby Atmos", "jack": "Tidak ada", "tambahan": "-" },
    "comms": { "wifi": "Wi-Fi 6E", "bluetooth": "5.3", "nfc": true, "infrared": false, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint samping", "Accelerometer", "Gyro", "Proximity", "Kompas", "Barometer"],
    "battery": { "kapasitas": 3700, "tipe": "Li-Po 3700 mAh", "charging": "25W kabel, 15W wireless", "wireless": true },
    "prices": [
      { "toko": "Samsung Official Store", "harga": 15999000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Erafone", "harga": 14999000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Lipat ringkas masuk kantong", "Cover screen 3.4 inci fungsional", "Snapdragon 8 Gen 2 kencang", "FlexCam unik untuk konten"],
    "cons": ["Baterai kecil 3700 mAh", "Kamera hanya dua, tanpa tele", "Harga mahal untuk speknya"]
  },
  {
    "id": "oneplus-12",
    "name": "OnePlus 12 5G",
    "brand": "OnePlus",
    "released": "2024-01-30",
    "status": "Tersedia",
    "priceIDR": 13999000,
    "priceUSD": 799,
    "rating": 4.6,
    "reviewCount": 540,
    "hits": 980340,
    "antutu": 2060000,
    "colors": ["Silky Black", "Flowy Emerald"],
    "colorHex": ["#1c1c1e", "#3d5a54"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM", "dukungan5G": true },
    "launch": { "diumumkan": "04 Des 2023", "rilis": "30 Jan 2024", "status": "Tersedia" },
    "body": { "dimensi": "163.3 x 75.8 x 9.2 mm", "berat": "220 g", "material": "Gorilla Glass Victus 2, aluminium", "simDetail": "Dual Nano-SIM", "tahanAir": "IP65", "tambahan": "Alert Slider, IR Blaster" },
    "display": { "tipe": "LTPO AMOLED 120Hz, Dolby Vision, 4500 nits peak", "ukuran": "6.82 inci", "resolusi": "1440 x 3168 piksel, 510 ppi", "kecerahan": "4500 nits (peak)", "proteksi": "Gorilla Glass Victus 2", "refreshRate": 120, "sizeInch": 6.82 },
    "platform": { "os": "OxygenOS 14 Android 14", "chipset": "Snapdragon 8 Gen 3 (4 nm)", "cpu": "Octa-core 3.3GHz", "gpu": "Adreno 750" },
    "memory": { "slotKartu": "Tidak", "ram": [12, 16], "ramUtama": 16, "internal": [256, 512], "storageUtama": 256, "tipe": "UFS 4.0" },
    "mainCamera": { "konfigurasi": "50MP Sony LYT-808 OIS + 64MP periskop 3x + 48MP ultrawide (Hasselblad)", "detail": "50 MP LYT-808 | 64 MP OV64B periskop 3x | 48 MP IMX581 ultrawide", "fitur": "Hasselblad color, OIS", "video": "8K@24fps, 4K@120fps Dolby Vision" },
    "selfieCamera": { "resolusi": "32 MP, f/2.4", "fitur": "Auto HDR", "video": "4K@30fps" },
    "sound": { "pengeras": "Stereo, Dolby Atmos", "jack": "Tidak ada", "tambahan": "Hi-Res" },
    "comms": { "wifi": "Wi-Fi 7", "bluetooth": "5.4", "nfc": true, "infrared": true, "usb": "USB-C 3.2", "gps": "GPS dual-band", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5400, "tipe": "Li-Po 5400 mAh", "charging": "100W kabel (100% 26 mnt) + 50W wireless AIRVOOC", "wireless": true },
    "prices": [
      { "toko": "OnePlus Official", "harga": 13999000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Distributor 1 tahun" },
      { "toko": "Tokopedia - OnePlus ID", "harga": 13499000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Distributor 1 tahun" }
    ],
    "pros": ["AnTuTu tertinggi 2 juta+", "Layar 4500 nits paling terang", "Charging 100W + wireless 50W", "Kamera Hasselblad lengkap"],
    "cons": ["IP65 saja, bukan IP68", "Tidak resmi Indonesia", "OxygenOS makin mirip ColorOS"]
  }
];

const NEWS = [
  { "id": 1, "judul": "Samsung Galaxy S25 Ultra bocor: Snapdragon 8 Elite, kamera 200MP baru", "kategori": "Rumor", "tanggal": "2026-09-28", "ringkasan": "Render CAD mengungkap sudut membulat, bezel 0.8mm, dan RAM 16GB untuk pertama kalinya di seri Ultra.", "isi": "Berdasarkan dokumen sertifikasi dan render OnLeaks, Galaxy S25 Ultra akan memakai Snapdragon 8 Elite for Galaxy, layar 6.9 inci QHD+ 3000 nits, dan kamera ultrawide 50MP baru. Baterai tetap 5000 mAh dengan charging 45W. Peluncuran diprediksi Januari 2026 dengan harga mulai Rp 22,9 juta." },
  { "id": 2, "judul": "POCO X6 Pro vs Redmi Note 13 Pro: mana yang layak dibeli 2026?", "kategori": "Komparasi", "tanggal": "2026-09-20", "ringkasan": "Selisih Rp 500 ribu, beda kelas performa. Kami uji gaming, kamera, dan baterai keduanya.", "isi": "POCO X6 Pro unggul jauh di performa (Dimensity 8300 Ultra, AnTuTu 1,4 juta vs 608 ribu) dan cocok untuk gaming. Redmi Note 13 Pro 5G menang di kamera 200MP dengan OIS lebih stabil dan layar dengan bezel lebih tipis. Jika prioritas gaming pilih POCO, jika kamera dan desain pilih Redmi." },
  { "id": 3, "judul": "Infinix Note 40 Pro 5G resmi: HP 3 jutaan pertama dengan wireless charging", "kategori": "Peluncuran", "tanggal": "2026-09-12", "ringkasan": "70W kabel + 20W wireless MagCharge, layar AMOLED curved 120Hz, speaker JBL.", "isi": "Infinix Note 40 Pro 5G resmi masuk Indonesia Rp 3.499.000 (8/256GB). Keunggulannya adalah wireless charging 20W magnetik pertama di harga 3 jutaan, layar curved 6.78 inci AMOLED, dan kamera 108MP OIS. Paket penjualan termasuk MagPad dan MagCase." },
  { "id": 4, "judul": "Tips: cara cek HP second agar tidak tertipu refurbish", "kategori": "Tips", "tanggal": "2026-09-05", "ringkasan": "Cek IMEI, sensor, baterai health, dan segel baut sebelum bayar.", "isi": "1) Cek IMEI di kemenperin.go.id. 2) Tes semua sensor via kode *#0*# (Samsung) atau aplikasi Phone Doctor. 3) Cek battery health di atas 85 persen. 4) Periksa segel baut dan bekas lem LCD. 5) Lakukan reset pabrik di tempat dan login ulang akun." }
];

module.exports = { PHONES, NEWS };
