const PHONES = [
  {
    "id": "samsung-galaxy-s24-ultra",
    "name": "Samsung Galaxy S24 Ultra",
    "brand": "Samsung",
    "released": "2024-01-24",
    "status": "Tersedia",
    "priceIDR": 21999000,
    "priceUSD": 1299,
    "rating": 4.8,
    "reviewCount": 2314,
    "hits": 5840201,
    "antutu": 1745852,
    "colors": ["Titanium Black", "Titanium Gray", "Titanium Violet", "Titanium Yellow"],
    "colorHex": ["#2b2b2e", "#8a8d91", "#b9a7c9", "#e8d48b"],
    "network": { "teknologi": "GSM / CDMA / HSPA / EVDO / LTE / 5G", "sim": "Nano-SIM + eSIM / Dual Nano-SIM", "dukungan5G": true },
    "launch": { "diumumkan": "17 Jan 2024", "rilis": "24 Jan 2024", "status": "Tersedia" },
    "body": { "dimensi": "162.3 x 79 x 8.6 mm", "berat": "232 g", "material": "Titanium frame, Gorilla Armor depan, kaca belakang", "simDetail": "Dual SIM (Nano + eSIM)", "tahanAir": "IP68 (1.5m, 30 mnt)", "tambahan": "S Pen built-in, latency 2.8ms" },
    "display": { "tipe": "Dynamic AMOLED 2X, 120Hz, HDR10+", "ukuran": "6.8 inci", "resolusi": "1440 x 3120 piksel, 505 ppi", "kecerahan": "2600 nits (peak)", "proteksi": "Corning Gorilla Armor", "refreshRate": 120, "sizeInch": 6.8 },
    "platform": { "os": "Android 14, One UI 6.1 (upgrade s/d Android 21)", "chipset": "Snapdragon 8 Gen 3 (4 nm)", "cpu": "Octa-core (1x3.39GHz + 3x3.1GHz + 2x2.9GHz + 2x2.2GHz)", "gpu": "Adreno 750" },
    "memory": { "slotKartu": "Tidak", "ram": [8, 12], "ramUtama": 12, "internal": [256, 512, 1024], "storageUtama": 256, "tipe": "UFS 4.0" },
    "mainCamera": { "konfigurasi": "200MP wide + 12MP ultrawide + 10MP tele 3x + 50MP periskop 5x", "detail": "200 MP, f/1.7, 24mm (wide), OIS | 12 MP, f/2.2, 13mm (ultrawide) | 10 MP, f/2.4, 67mm (tele 3x) | 50 MP, f/3.4, 111mm (periskop 5x)", "fitur": "Laser AF, OIS, zoom optik 5x, zoom digital 100x, Super Steady", "video": "8K@24fps, 4K@30/60/120fps, 1080p@240fps, HDR10+" },
    "selfieCamera": { "resolusi": "12 MP, f/2.2, 26mm (wide)", "fitur": "Dual Pixel PDAF, HDR", "video": "4K@30/60fps" },
    "sound": { "pengeras": "Stereo (AKG), Dolby Atmos", "jack": "Tidak ada", "tambahan": "Audio 32-bit/384kHz" },
    "comms": { "wifi": "Wi-Fi 802.11 a/b/g/n/ac/6e/7, tri-band, Wi-Fi Direct", "bluetooth": "5.3, A2DP, LE", "nfc": true, "infrared": false, "usb": "USB-C 3.2, OTG, DisplayPort 1.2", "gps": "GPS, GLONASS, BDS, GALILEO, QZSS", "uwb": true },
    "sensors": ["Fingerprint ultrasonik di layar", "Accelerometer", "Gyro", "Proximity", "Kompas", "Barometer"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Ion 5000 mAh", "charging": "45W kabel (65% dalam 30 mnt), 15W wireless, 4.5W reverse", "wireless": true },
    "prices": [
      { "toko": "Samsung Official Store", "harga": 21999000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Erafone", "harga": 21499000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Rp 18.000", "garansi": "Resmi 1 tahun" },
      { "toko": "Tokopedia - GadgetHub", "harga": 20750000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Shopee - CellWorld", "harga": 20499000, "stok": "2 unit", "ratingToko": 4.6, "ongkir": "Gratis", "garansi": "Distributor 1 tahun" }
    ],
    "pros": ["Kamera 200MP terbaik di kelasnya dengan zoom 5x tajam", "Snapdragon 8 Gen 3 sangat kencang dan efisien", "S Pen bawaan produktif", "Update 7 tahun"],
    "cons": ["Harga tinggi", "Pengisian 45W kalah dari rival China", "Bodi besar dan berat"]
  },
  {
    "id": "iphone-15-pro-max",
    "name": "Apple iPhone 15 Pro Max",
    "brand": "Apple",
    "released": "2023-09-22",
    "status": "Tersedia",
    "priceIDR": 24999000,
    "priceUSD": 1199,
    "rating": 4.9,
    "reviewCount": 3102,
    "hits": 6120450,
    "antutu": 1642280,
    "colors": ["Natural Titanium", "Blue Titanium", "White Titanium", "Black Titanium"],
    "colorHex": ["#c2b8a3", "#3b4453", "#e3e4e6", "#1c1c1e"],
    "network": { "teknologi": "GSM / CDMA / HSPA / EVDO / LTE / 5G", "sim": "Nano-SIM + eSIM / Dual eSIM", "dukungan5G": true },
    "launch": { "diumumkan": "12 Sep 2023", "rilis": "22 Sep 2023", "status": "Tersedia" },
    "body": { "dimensi": "159.9 x 76.7 x 8.3 mm", "berat": "221 g", "material": "Titanium frame, Ceramic Shield depan", "simDetail": "Dual eSIM / Nano-SIM + eSIM", "tahanAir": "IP68 (6m, 30 mnt)", "tambahan": "Action Button, USB-C" },
    "display": { "tipe": "LTPO Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision", "ukuran": "6.7 inci", "resolusi": "1290 x 2796 piksel, 460 ppi", "kecerahan": "2000 nits (peak outdoor)", "proteksi": "Ceramic Shield", "refreshRate": 120, "sizeInch": 6.7 },
    "platform": { "os": "iOS 17 (upgrade ke iOS 18)", "chipset": "Apple A17 Pro (3 nm)", "cpu": "Hexa-core (2x3.78GHz + 4x2.11GHz)", "gpu": "Apple GPU 6-core, ray tracing" },
    "memory": { "slotKartu": "Tidak", "ram": [8], "ramUtama": 8, "internal": [256, 512, 1024], "storageUtama": 256, "tipe": "NVMe" },
    "mainCamera": { "konfigurasi": "48MP wide + 12MP ultrawide + 12MP periskop 5x", "detail": "48 MP, f/1.8, 24mm (wide), sensor-shift OIS | 12 MP, f/2.2 (ultrawide) | 12 MP, f/2.8, 120mm (periskop 5x)", "fitur": "LiDAR, Photonic Engine, ProRAW, Night mode", "video": "4K@24/30/60fps, ProRes, Log, ACES" },
    "selfieCamera": { "resolusi": "12 MP, f/1.9, 23mm + SL 3D", "fitur": "Face ID, HDR, Cinematic mode", "video": "4K@30/60fps" },
    "sound": { "pengeras": "Stereo, Dolby Atmos, Spatial Audio", "jack": "Tidak ada", "tambahan": "Audio Zoom" },
    "comms": { "wifi": "Wi-Fi 6E, tri-band", "bluetooth": "5.3", "nfc": true, "infrared": false, "usb": "USB-C 3.2 Gen 2, DisplayPort", "gps": "GPS presisi ganda, GLONASS, GALILEO, QZSS, BeiDou", "uwb": true },
    "sensors": ["Face ID", "LiDAR Scanner", "Accelerometer", "Gyro", "Proximity", "Kompas", "Barometer"],
    "battery": { "kapasitas": 4422, "tipe": "Li-Ion 4422 mAh", "charging": "27W kabel (50% 30 mnt, PD2.0), 15W MagSafe/Qi2", "wireless": true },
    "prices": [
      { "toko": "iBox Official", "harga": 24999000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi Apple 1 tahun" },
      { "toko": "Digimap", "harga": 24499000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi Apple 1 tahun" },
      { "toko": "Tokopedia - iStyle", "harga": 23750000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Resmi Apple 1 tahun" }
    ],
    "pros": ["Chip A17 Pro terkencang dengan ray tracing", "Material titanium ringan dan premium", "Kamera ProRes untuk videografer", "USB-C 3.2 cepat"],
    "cons": ["Harga paling mahal", "Pengisian lambat 27W", "Tidak ada Touch ID"]
  },
  {
    "id": "xiaomi-redmi-note-13-pro",
    "name": "Xiaomi Redmi Note 13 Pro 5G",
    "brand": "Xiaomi",
    "released": "2024-01-15",
    "status": "Tersedia",
    "priceIDR": 4299000,
    "priceUSD": 299,
    "rating": 4.6,
    "reviewCount": 5871,
    "hits": 4210330,
    "antutu": 608761,
    "colors": ["Midnight Black", "Ocean Teals", "Lavender Purple"],
    "colorHex": ["#15161a", "#2e6f73", "#b9a7d6"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM", "dukungan5G": true },
    "launch": { "diumumkan": "04 Jan 2024", "rilis": "15 Jan 2024", "status": "Tersedia" },
    "body": { "dimensi": "161.1 x 74.9 x 7.98 mm", "berat": "187 g", "material": "Gorilla Glass Victus depan, plastik belakang", "simDetail": "Dual Nano-SIM", "tahanAir": "IP54", "tambahan": "IR Blaster, jack 3.5mm" },
    "display": { "tipe": "AMOLED CrystalRes, 120Hz, HDR10+, Dolby Vision", "ukuran": "6.67 inci", "resolusi": "1220 x 2712 piksel, 446 ppi", "kecerahan": "1800 nits (peak)", "proteksi": "Gorilla Glass Victus", "refreshRate": 120, "sizeInch": 6.67 },
    "platform": { "os": "MIUI 14 berbasis Android 13 (upgrade HyperOS)", "chipset": "Snapdragon 7s Gen 2 (4 nm)", "cpu": "Octa-core (4x2.40GHz + 4x1.95GHz)", "gpu": "Adreno 710" },
    "memory": { "slotKartu": "Tidak", "ram": [8, 12], "ramUtama": 8, "internal": [256, 512], "storageUtama": 256, "tipe": "UFS 2.2" },
    "mainCamera": { "konfigurasi": "200MP wide + 8MP ultrawide + 2MP macro", "detail": "200 MP, f/1.7, OIS | 8 MP, f/2.2 ultrawide | 2 MP macro", "fitur": "OIS, Night mode, 4x lossless zoom sensor", "video": "4K@30fps, 1080p@30/60fps, gyro-EIS" },
    "selfieCamera": { "resolusi": "16 MP, f/2.4", "fitur": "HDR, beautify", "video": "1080p@30/60fps" },
    "sound": { "pengeras": "Stereo ganda, Dolby Atmos", "jack": "Ada, 3.5mm", "tambahan": "Hi-Res Audio" },
    "comms": { "wifi": "Wi-Fi ac, dual-band", "bluetooth": "5.2", "nfc": true, "infrared": true, "usb": "USB-C 2.0, OTG", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5100, "tipe": "Li-Po 5100 mAh", "charging": "67W turbo (100% 44 mnt)", "wireless": false },
    "prices": [
      { "toko": "Xiaomi Official Store", "harga": 4299000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Erafone", "harga": 4199000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Rp 12.000", "garansi": "Resmi 1 tahun" },
      { "toko": "Shopee - Mi Store", "harga": 3999000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Tokopedia - Fonel", "harga": 3899000, "stok": "5 unit", "ratingToko": 4.6, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Layar AMOLED 1.5K flagship di harga mid-range", "Kamera 200MP OIS", "Charging 67W cepat", "Ada jack 3.5mm dan IR blaster"],
    "cons": ["Chipset 7s Gen 2 bukan untuk gaming berat", "Storage UFS 2.2", "Tahan air hanya IP54"]
  },
  {
    "id": "oppo-reno-11-pro",
    "name": "Oppo Reno 11 Pro 5G",
    "brand": "Oppo",
    "released": "2024-01-20",
    "status": "Tersedia",
    "priceIDR": 8999000,
    "priceUSD": 549,
    "rating": 4.5,
    "reviewCount": 1290,
    "hits": 1874220,
    "antutu": 868000,
    "colors": ["Pearl White", "Rock Grey"],
    "colorHex": ["#ece7dd", "#4a4d52"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM", "dukungan5G": true },
    "launch": { "diumumkan": "10 Jan 2024", "rilis": "20 Jan 2024", "status": "Tersedia" },
    "body": { "dimensi": "162.4 x 74.1 x 7.6 mm", "berat": "190 g", "material": "Kaca depan-belakang, frame plastik", "simDetail": "Dual Nano-SIM", "tahanAir": "IP54", "tambahan": "IR Blaster" },
    "display": { "tipe": "AMOLED 120Hz, HDR10+", "ukuran": "6.7 inci", "resolusi": "1080 x 2412 piksel, 394 ppi", "kecerahan": "1600 nits (peak)", "proteksi": "Asahi Glass AGC DT-Star2", "refreshRate": 120, "sizeInch": 6.7 },
    "platform": { "os": "ColorOS 14 berbasis Android 14", "chipset": "Dimensity 8200 (4 nm)", "cpu": "Octa-core (1x3.1GHz + 3x3.0GHz + 4x2.0GHz)", "gpu": "Mali-G610 MC6" },
    "memory": { "slotKartu": "Tidak", "ram": [12], "ramUtama": 12, "internal": [512], "storageUtama": 512, "tipe": "UFS 3.1" },
    "mainCamera": { "konfigurasi": "50MP wide OIS + 32MP tele 2x + 8MP ultrawide (Hasselblad tuned)", "detail": "50 MP Sony IMX890, f/1.8, OIS | 32 MP IMX709 tele 2x | 8 MP ultrawide", "fitur": "Hasselblad Portrait, OIS, 2x optical", "video": "4K@30/60fps, gyro-EIS" },
    "selfieCamera": { "resolusi": "32 MP, f/2.4, AF", "fitur": "Portrait, HDR", "video": "4K@30fps" },
    "sound": { "pengeras": "Stereo, Dolby Atmos", "jack": "Tidak ada", "tambahan": "Hi-Res" },
    "comms": { "wifi": "Wi-Fi 6, dual-band", "bluetooth": "5.3", "nfc": true, "infrared": true, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 4600, "tipe": "Li-Po 4600 mAh", "charging": "80W SuperVOOC (100% 30 mnt), reverse wired", "wireless": false },
    "prices": [
      { "toko": "Oppo Official Store", "harga": 8999000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Erafone", "harga": 8799000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Tokopedia - Oppo Gallery", "harga": 8499000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Kamera portrait Hasselblad sangat natural", "Desain tipis ringan premium", "Charging 80W sangat cepat", "Selfie 32MP AF tajam"],
    "cons": ["Baterai 4600 mAh tergolong kecil", "Tidak ada ultrawide telefoto panjang", "Harga naik dari pendahulu"]
  },
  {
    "id": "vivo-v30-pro",
    "name": "Vivo V30 Pro 5G",
    "brand": "Vivo",
    "released": "2024-03-05",
    "status": "Tersedia",
    "priceIDR": 8499000,
    "priceUSD": 519,
    "rating": 4.6,
    "reviewCount": 980,
    "hits": 1540890,
    "antutu": 912450,
    "colors": ["Bloom White", "Waving Aqua"],
    "colorHex": ["#f2ede6", "#7fb8b5"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM", "dukungan5G": true },
    "launch": { "diumumkan": "28 Feb 2024", "rilis": "05 Mar 2024", "status": "Tersedia" },
    "body": { "dimensi": "164.4 x 75.1 x 7.5 mm", "berat": "188 g", "material": "Kaca depan-belakang 3D curved", "simDetail": "Dual Nano-SIM", "tahanAir": "IP54", "tambahan": "Aura Light Portrait 3.0" },
    "display": { "tipe": "AMOLED 120Hz, HDR10+", "ukuran": "6.78 inci", "resolusi": "1260 x 2800 piksel, 453 ppi", "kecerahan": "2800 nits (peak)", "proteksi": "Schott Xensation", "refreshRate": 120, "sizeInch": 6.78 },
    "platform": { "os": "Funtouch 14 berbasis Android 14", "chipset": "Dimensity 8200 (4 nm)", "cpu": "Octa-core (1x3.1GHz + 3x3.0GHz + 4x2.0GHz)", "gpu": "Mali-G610 MC6" },
    "memory": { "slotKartu": "Tidak", "ram": [12], "ramUtama": 12, "internal": [512], "storageUtama": 512, "tipe": "UFS 3.1" },
    "mainCamera": { "konfigurasi": "50MP wide ZEISS + 50MP ultrawide + 50MP portrait 2x", "detail": "3x 50MP ZEISS: IMX920 wide OIS +超 wide + IMX816 portrait", "fitur": "ZEISS optics, Aura Light, OIS", "video": "4K@30fps" },
    "selfieCamera": { "resolusi": "50 MP, f/2.0, AF, wide", "fitur": "ZEISS, dual soft LED", "video": "4K@30fps" },
    "sound": { "pengeras": "Mono + stereo virtual", "jack": "Tidak ada", "tambahan": "Hi-Res" },
    "comms": { "wifi": "Wi-Fi ac dual-band", "bluetooth": "5.3", "nfc": true, "infrared": false, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "80W FlashCharge (100% 33 mnt)", "wireless": false },
    "prices": [
      { "toko": "Vivo Official Store", "harga": 8499000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Erafone", "harga": 8299000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Semua kamera 50MP ZEISS, langka di kelasnya", "Layar 2800 nits sangat terang", "Bodi tipis 7.5mm", "Selfie 50MP AF terbaik"],
    "cons": ["Video hanya 4K30, tanpa 60fps", "Speaker belum stereo penuh", "Funtouch banyak bloatware"]
  },
  {
    "id": "samsung-galaxy-a54",
    "name": "Samsung Galaxy A54 5G",
    "brand": "Samsung",
    "released": "2023-03-24",
    "status": "Tersedia",
    "priceIDR": 5999000,
    "priceUSD": 449,
    "rating": 4.5,
    "reviewCount": 4210,
    "hits": 3980110,
    "antutu": 536943,
    "colors": ["Awesome Lime", "Awesome Graphite", "Awesome Violet", "Awesome White"],
    "colorHex": ["#b8d94e", "#3a3b3d", "#b9a7d6", "#f2f2f2"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Single/Dual Nano-SIM + microSD hybrid", "dukungan5G": true },
    "launch": { "diumumkan": "15 Mar 2023", "rilis": "24 Mar 2023", "status": "Tersedia" },
    "body": { "dimensi": "158.2 x 76.7 x 8.2 mm", "berat": "202 g", "material": "Gorilla Glass 5 depan-belakang", "simDetail": "Hybrid Dual SIM + microSD s/d 1TB", "tahanAir": "IP67", "tambahan": "-" },
    "display": { "tipe": "Super AMOLED 120Hz, HDR10+", "ukuran": "6.4 inci", "resolusi": "1080 x 2340 piksel, 403 ppi", "kecerahan": "1000 nits (HBM)", "proteksi": "Gorilla Glass 5", "refreshRate": 120, "sizeInch": 6.4 },
    "platform": { "os": "One UI 5.1 Android 13 (upgrade ke Android 17)", "chipset": "Exynos 1380 (5 nm)", "cpu": "Octa-core (4x2.4GHz + 4x2.0GHz)", "gpu": "Mali-G68 MP5" },
    "memory": { "slotKartu": "Ya, hybrid microSD s/d 1TB", "ram": [6, 8], "ramUtama": 8, "internal": [128, 256], "storageUtama": 256, "tipe": "UFS 2.2" },
    "mainCamera": { "konfigurasi": "50MP wide OIS + 12MP ultrawide + 5MP macro", "detail": "50 MP, f/1.8, OIS | 12 MP ultrawide | 5 MP macro", "fitur": "OIS, Nightography, VDIS", "video": "4K@30fps, gyro-EIS" },
    "selfieCamera": { "resolusi": "32 MP, f/2.2", "fitur": "HDR", "video": "4K@30fps" },
    "sound": { "pengeras": "Stereo, Dolby Atmos", "jack": "Tidak ada", "tambahan": "-" },
    "comms": { "wifi": "Wi-Fi 6, dual-band, Wi-Fi Direct", "bluetooth": "5.3", "nfc": true, "infrared": false, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "25W (50% 30 mnt)", "wireless": false },
    "prices": [
      { "toko": "Samsung Official Store", "harga": 5999000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Tokopedia - Terlaris", "harga": 5299000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Shopee - Star Seller", "harga": 5199000, "stok": "Ready", "ratingToko": 4.6, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["IP67 + Gorilla Glass 5 kokoh", "Ada slot microSD", "Update 4+5 tahun", "Kamera OIS stabil"],
    "cons": ["Charging hanya 25W", "Exynos 1380 panas saat gaming", "Bezel agak tebal"]
  },
  {
    "id": "poco-x6-pro",
    "name": "POCO X6 Pro 5G",
    "brand": "Xiaomi",
    "released": "2024-01-25",
    "status": "Tersedia",
    "priceIDR": 4799000,
    "priceUSD": 329,
    "rating": 4.7,
    "reviewCount": 3450,
    "hits": 2876540,
    "antutu": 1410000,
    "colors": ["Black", "Yellow", "Grey"],
    "colorHex": ["#1b1b1d", "#e8c832", "#6b6e73"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM", "dukungan5G": true },
    "launch": { "diumumkan": "11 Jan 2024", "rilis": "25 Jan 2024", "status": "Tersedia" },
    "body": { "dimensi": "160.5 x 74.3 x 8.3 mm", "berat": "190 g", "material": "Plastik vegan leather (varian kuning)", "simDetail": "Dual Nano-SIM", "tahanAir": "IP54", "tambahan": "IR Blaster" },
    "display": { "tipe": "AMOLED CrystalRes 120Hz, Dolby Vision, 68B warna", "ukuran": "6.67 inci", "resolusi": "1220 x 2712 piksel", "kecerahan": "1800 nits peak", "proteksi": "Gorilla Glass 5", "refreshRate": 120, "sizeInch": 6.67 },
    "platform": { "os": "HyperOS berbasis Android 14", "chipset": "Dimensity 8300 Ultra (4 nm)", "cpu": "Octa-core (1x3.35GHz + 3x3.0GHz + 4x2.2GHz)", "gpu": "Mali-G615 MC6" },
    "memory": { "slotKartu": "Tidak", "ram": [8, 12], "ramUtama": 12, "internal": [256, 512], "storageUtama": 512, "tipe": "UFS 4.0" },
    "mainCamera": { "konfigurasi": "64MP wide OIS + 8MP ultrawide + 2MP macro", "detail": "64 MP Omnivision OV64B, f/1.7, OIS", "fitur": "OIS, Night mode", "video": "4K@30fps" },
    "selfieCamera": { "resolusi": "16 MP", "fitur": "HDR", "video": "1080p@30fps" },
    "sound": { "pengeras": "Stereo, Dolby Atmos", "jack": "Tidak ada", "tambahan": "Hi-Res" },
    "comms": { "wifi": "Wi-Fi 6", "bluetooth": "5.4", "nfc": true, "infrared": true, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "67W turbo", "wireless": false },
    "prices": [
      { "toko": "POCO Official Store", "harga": 4799000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Shopee - POCO ID", "harga": 4599000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Dimensity 8300 Ultra terkencang di harga 4 jutaan, AnTuTu 1.4 jt", "UFS 4.0 + RAM 12GB", "Layar 1.5K flagship", "Value for money terbaik"],
    "cons": ["Kamera biasa saja", "Bloatware HyperOS", "Material plastik"]
  },
  {
    "id": "realme-11-pro-plus",
    "name": "Realme 11 Pro+ 5G",
    "brand": "Realme",
    "released": "2023-07-18",
    "status": "Tersedia",
    "priceIDR": 6999000,
    "priceUSD": 429,
    "rating": 4.4,
    "reviewCount": 1120,
    "hits": 1320450,
    "antutu": 541402,
    "colors": ["Sunrise Beige", "Oasis Green", "Astral Black"],
    "colorHex": ["#e6d5b8", "#3d5a4c", "#1c1c1e"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM", "dukungan5G": true },
    "launch": { "diumumkan": "10 Mei 2023", "rilis": "18 Jul 2023", "status": "Tersedia" },
    "body": { "dimensi": "161.6 x 73.9 x 8.2 mm", "berat": "183 g", "material": "Vegan leather + kaca curved", "simDetail": "Dual Nano-SIM", "tahanAir": "-", "tambahan": "Desain kolaborasi Matteo Menotto" },
    "display": { "tipe": "AMOLED curved 120Hz, HDR10+", "ukuran": "6.7 inci", "resolusi": "1080 x 2412 piksel", "kecerahan": "950 nits", "proteksi": "Tidak disebutkan", "refreshRate": 120, "sizeInch": 6.7 },
    "platform": { "os": "Realme UI 4.0 Android 13", "chipset": "Dimensity 7050 (6 nm)", "cpu": "Octa-core (2x2.6GHz + 6x2.0GHz)", "gpu": "Mali-G68 MC4" },
    "memory": { "slotKartu": "Tidak", "ram": [12], "ramUtama": 12, "internal": [512], "storageUtama": 512, "tipe": "UFS 3.1" },
    "mainCamera": { "konfigurasi": "200MP Samsung HP3 OIS + 8MP ultrawide + 2MP macro", "detail": "200 MP, f/1.7, OIS, 4x lossless zoom", "fitur": "OIS, Street mode", "video": "4K@30fps" },
    "selfieCamera": { "resolusi": "32 MP Sony IMX615", "fitur": "Portrait", "video": "1080p@30fps" },
    "sound": { "pengeras": "Stereo ganda, Dolby Atmos", "jack": "Tidak ada", "tambahan": "Hi-Res" },
    "comms": { "wifi": "Wi-Fi 6", "bluetooth": "5.2", "nfc": true, "infrared": false, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "100W SuperVOOC (100% 26 mnt)", "wireless": false },
    "prices": [
      { "toko": "Realme Official Store", "harga": 6999000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Erafone", "harga": 6799000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Desain vegan leather premium dan unik", "Charging 100W tercepat di kelasnya", "Kamera 200MP dengan 4x lossless", "Layar curved mewah"],
    "cons": ["Chipset hanya Dimensity 7050", "Tanpa IP rating", "Video selfie mentok 1080p"]
  },
  {
    "id": "infinix-note-40-pro",
    "name": "Infinix Note 40 Pro 5G",
    "brand": "Infinix",
    "released": "2024-04-02",
    "status": "Tersedia",
    "priceIDR": 3499000,
    "priceUSD": 229,
    "rating": 4.5,
    "reviewCount": 2870,
    "hits": 2103400,
    "antutu": 452310,
    "colors": ["Titan Gold", "Obsidian Black"],
    "colorHex": ["#c9a86a", "#1c1c1e"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM", "dukungan5G": true },
    "launch": { "diumumkan": "18 Mar 2024", "rilis": "02 Apr 2024", "status": "Tersedia" },
    "body": { "dimensi": "164.4 x 74.6 x 7.8 mm", "berat": "190 g", "material": "Kaca curved, frame plastik", "simDetail": "Dual Nano-SIM + microSD", "tahanAir": "IP54", "tambahan": "Wireless MagCharge + JBL audio" },
    "display": { "tipe": "AMOLED curved 120Hz", "ukuran": "6.78 inci", "resolusi": "1080 x 2436 piksel", "kecerahan": "1300 nits peak", "proteksi": "Gorilla Glass", "refreshRate": 120, "sizeInch": 6.78 },
    "platform": { "os": "XOS 14 Android 14", "chipset": "Dimensity 7020 (6 nm)", "cpu": "Octa-core (2x2.2GHz + 6x2.0GHz)", "gpu": "IMG BXM-8-256" },
    "memory": { "slotKartu": "Ya, microSD", "ram": [8], "ramUtama": 8, "internal": [256], "storageUtama": 256, "tipe": "UFS 2.2" },
    "mainCamera": { "konfigurasi": "108MP wide OIS + 2MP macro + 2MP depth", "detail": "108 MP, f/1.8, OIS, 3x lossless zoom", "fitur": "OIS, Super Night", "video": "1440p@30fps" },
    "selfieCamera": { "resolusi": "32 MP, f/2.0", "fitur": "Dual LED flash", "video": "1080p@30fps" },
    "sound": { "pengeras": "Stereo JBL, Hi-Res", "jack": "Ada, 3.5mm", "tambahan": "Audio JBL tuned" },
    "comms": { "wifi": "Wi-Fi ac", "bluetooth": "5.2", "nfc": true, "infrared": true, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "70W kabel + 20W wireless MagCharge", "wireless": true },
    "prices": [
      { "toko": "Infinix Official Store", "harga": 3499000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Shopee - Infinix", "harga": 3299000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Satu-satunya 3 jutaan dengan wireless charging 20W", "Layar curved AMOLED", "Speaker JBL stereo", "Kamera 108MP OIS"],
    "cons": ["Chipset Dimensity 7020 pas-pasan", "Update software hanya 2 tahun", "Ultrawide tidak ada"]
  },
  {
    "id": "google-pixel-8-pro",
    "name": "Google Pixel 8 Pro",
    "brand": "Google",
    "released": "2023-10-12",
    "status": "Tersedia",
    "priceIDR": 15999000,
    "priceUSD": 999,
    "rating": 4.7,
    "reviewCount": 860,
    "hits": 1980220,
    "antutu": 1150240,
    "colors": ["Obsidian", "Porcelain", "Bay"],
    "colorHex": ["#1c1c1e", "#e8e0d5", "#a8c7fa"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Nano-SIM + eSIM", "dukungan5G": true },
    "launch": { "diumumkan": "04 Okt 2023", "rilis": "12 Okt 2023", "status": "Tersedia" },
    "body": { "dimensi": "162.6 x 76.5 x 8.8 mm", "berat": "213 g", "material": "Gorilla Glass Victus 2 depan-belakang, aluminium", "simDetail": "Nano-SIM + eSIM", "tahanAir": "IP68", "tambahan": "Sensor suhu" },
    "display": { "tipe": "LTPO OLED Super Actua 120Hz", "ukuran": "6.7 inci", "resolusi": "1344 x 2992 piksel", "kecerahan": "2400 nits peak", "proteksi": "Gorilla Glass Victus 2", "refreshRate": 120, "sizeInch": 6.7 },
    "platform": { "os": "Android 14 (update 7 tahun)", "chipset": "Google Tensor G3 (4 nm)", "cpu": "Nona-core (1x3.0GHz + 4x2.45GHz + 4x2.15GHz)", "gpu": "Immortalis-G715s MC10" },
    "memory": { "slotKartu": "Tidak", "ram": [12], "ramUtama": 12, "internal": [128, 256, 512], "storageUtama": 128, "tipe": "UFS 3.1" },
    "mainCamera": { "konfigurasi": "50MP wide + 48MP ultrawide + 48MP tele 5x", "detail": "50 MP, f/1.7, OIS | 48 MP ultrawide | 48 MP tele 5x OIS", "fitur": "Magic Editor, Best Take, Night Sight, Pro controls", "video": "4K@60fps, 8K upscaling (Video Boost)" },
    "selfieCamera": { "resolusi": "10.5 MP, f/2.2, AF", "fitur": "Auto focus", "video": "4K@30fps" },
    "sound": { "pengeras": "Stereo", "jack": "Tidak ada", "tambahan": "Spatial Audio" },
    "comms": { "wifi": "Wi-Fi 7", "bluetooth": "5.3", "nfc": true, "infrared": false, "usb": "USB-C 3.2", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": true },
    "sensors": ["Fingerprint di layar", "Face Unlock", "Accelerometer", "Gyro", "Proximity", "Kompas", "Barometer", "Termometer"],
    "battery": { "kapasitas": 5050, "tipe": "Li-Po 5050 mAh", "charging": "30W kabel (50% 30 mnt), 23W wireless", "wireless": true },
    "prices": [
      { "toko": "Google Store Partner", "harga": 15999000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Distributor 1 tahun" },
      { "toko": "Tokopedia - PixelID", "harga": 14999000, "stok": "Pre-order", "ratingToko": 4.6, "ongkir": "Gratis", "garansi": "Distributor 1 tahun" }
    ],
    "pros": ["Kamera komputasional terbaik, AI Magic Editor", "Update 7 tahun + Feature Drop", "Layar Super Actua 2400 nits", "Fitur AI Gemini eksklusif"],
    "cons": ["Tensor G3 panas dan kurang efisien", "Charging 30W lambat", "Tidak resmi di Indonesia"]
  },
  {
    "id": "samsung-galaxy-z-flip-5",
    "name": "Samsung Galaxy Z Flip 5",
    "brand": "Samsung",
    "released": "2023-08-11",
    "status": "Tersedia",
    "priceIDR": 15999000,
    "priceUSD": 999,
    "rating": 4.4,
    "reviewCount": 760,
    "hits": 1210890,
    "antutu": 1420500,
    "colors": ["Mint", "Graphite", "Cream", "Lavender"],
    "colorHex": ["#a8d5ba", "#3a3b3d", "#f5f0e1", "#c5b3e6"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Nano-SIM + eSIM", "dukungan5G": true },
    "launch": { "diumumkan": "26 Jul 2023", "rilis": "11 Agu 2023", "status": "Tersedia" },
    "body": { "dimensi": "Lipatan: 85.1 x 71.9 x 15.1 mm / Bentang: 165.1 x 71.9 x 6.9 mm", "berat": "187 g", "material": "Armor Aluminum, Gorilla Glass Victus 2", "simDetail": "Nano-SIM + eSIM", "tahanAir": "IPX8", "tambahan": "Flex Hinge zero-gap, cover screen 3.4 inci" },
    "display": { "tipe": "Foldable Dynamic AMOLED 2X 120Hz + cover 3.4 inci Super AMOLED", "ukuran": "6.7 inci utama", "resolusi": "1080 x 2640 piksel + 720 x 748 cover", "kecerahan": "1750 nits peak", "proteksi": "UTG", "refreshRate": 120, "sizeInch": 6.7 },
    "platform": { "os": "One UI 5.1.1 Android 13", "chipset": "Snapdragon 8 Gen 2 (4 nm)", "cpu": "Octa-core (1x3.36GHz + 2x2.8GHz + 2x2.8GHz + 3x2.0GHz)", "gpu": "Adreno 740" },
    "memory": { "slotKartu": "Tidak", "ram": [8], "ramUtama": 8, "internal": [256, 512], "storageUtama": 256, "tipe": "UFS 4.0" },
    "mainCamera": { "konfigurasi": "12MP wide OIS + 12MP ultrawide", "detail": "12 MP, f/1.8, OIS + 12 MP, f/2.2 ultrawide 123 derajat", "fitur": "FlexCam, auto framing", "video": "4K@60fps" },
    "selfieCamera": { "resolusi": "10 MP, f/2.2", "fitur": "HDR", "video": "4K@30fps" },
    "sound": { "pengeras": "Stereo, Dolby Atmos", "jack": "Tidak ada", "tambahan": "-" },
    "comms": { "wifi": "Wi-Fi 6E", "bluetooth": "5.3", "nfc": true, "infrared": false, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint samping", "Accelerometer", "Gyro", "Proximity", "Kompas", "Barometer"],
    "battery": { "kapasitas": 3700, "tipe": "Li-Po 3700 mAh", "charging": "25W kabel, 15W wireless", "wireless": true },
    "prices": [
      { "toko": "Samsung Official Store", "harga": 15999000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Erafone", "harga": 14999000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Lipat ringkas masuk kantong", "Cover screen 3.4 inci fungsional", "Snapdragon 8 Gen 2 kencang", "FlexCam unik untuk konten"],
    "cons": ["Baterai kecil 3700 mAh", "Kamera hanya dua, tanpa tele", "Harga mahal untuk speknya"]
  },
  {
    "id": "oneplus-12",
    "name": "OnePlus 12 5G",
    "brand": "OnePlus",
    "released": "2024-01-30",
    "status": "Tersedia",
    "priceIDR": 13999000,
    "priceUSD": 799,
    "rating": 4.6,
    "reviewCount": 540,
    "hits": 980340,
    "antutu": 2060000,
    "colors": ["Silky Black", "Flowy Emerald"],
    "colorHex": ["#1c1c1e", "#3d5a54"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM", "dukungan5G": true },
    "launch": { "diumumkan": "04 Des 2023", "rilis": "30 Jan 2024", "status": "Tersedia" },
    "body": { "dimensi": "163.3 x 75.8 x 9.2 mm", "berat": "220 g", "material": "Gorilla Glass Victus 2, aluminium", "simDetail": "Dual Nano-SIM", "tahanAir": "IP65", "tambahan": "Alert Slider, IR Blaster" },
    "display": { "tipe": "LTPO AMOLED 120Hz, Dolby Vision, 4500 nits peak", "ukuran": "6.82 inci", "resolusi": "1440 x 3168 piksel, 510 ppi", "kecerahan": "4500 nits (peak)", "proteksi": "Gorilla Glass Victus 2", "refreshRate": 120, "sizeInch": 6.82 },
    "platform": { "os": "OxygenOS 14 Android 14", "chipset": "Snapdragon 8 Gen 3 (4 nm)", "cpu": "Octa-core 3.3GHz", "gpu": "Adreno 750" },
    "memory": { "slotKartu": "Tidak", "ram": [12, 16], "ramUtama": 16, "internal": [256, 512], "storageUtama": 256, "tipe": "UFS 4.0" },
    "mainCamera": { "konfigurasi": "50MP Sony LYT-808 OIS + 64MP periskop 3x + 48MP ultrawide (Hasselblad)", "detail": "50 MP LYT-808 | 64 MP OV64B periskop 3x | 48 MP IMX581 ultrawide", "fitur": "Hasselblad color, OIS", "video": "8K@24fps, 4K@120fps Dolby Vision" },
    "selfieCamera": { "resolusi": "32 MP, f/2.4", "fitur": "Auto HDR", "video": "4K@30fps" },
    "sound": { "pengeras": "Stereo, Dolby Atmos", "jack": "Tidak ada", "tambahan": "Hi-Res" },
    "comms": { "wifi": "Wi-Fi 7", "bluetooth": "5.4", "nfc": true, "infrared": true, "usb": "USB-C 3.2", "gps": "GPS dual-band", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5400, "tipe": "Li-Po 5400 mAh", "charging": "100W kabel (100% 26 mnt) + 50W wireless AIRVOOC", "wireless": true },
    "prices": [
      { "toko": "OnePlus Official", "harga": 13999000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Distributor 1 tahun" },
      { "toko": "Tokopedia - OnePlus ID", "harga": 13499000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Distributor 1 tahun" }
    ],
    "pros": ["AnTuTu tertinggi 2 juta+", "Layar 4500 nits paling terang", "Charging 100W + wireless 50W", "Kamera Hasselblad lengkap"],
    "cons": ["IP65 saja, bukan IP68", "Tidak resmi Indonesia", "OxygenOS makin mirip ColorOS"]
  },
  {
    "id": "samsung-galaxy-a15-5g",
    "name": "Samsung Galaxy A15 5G",
    "brand": "Samsung",
    "released": "2023-12-20",
    "status": "Tersedia",
    "priceIDR": 3299000,
    "priceUSD": 199,
    "rating": 4.3,
    "reviewCount": 3120,
    "hits": 2650440,
    "antutu": 401200,
    "colors": ["Blue Black", "Light Blue", "Yellow"],
    "colorHex": ["#23262b", "#9fc3e0", "#e3c964"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM + microSD hybrid", "dukungan5G": true },
    "launch": { "diumumkan": "11 Des 2023", "rilis": "20 Des 2023", "status": "Tersedia" },
    "body": { "dimensi": "160.1 x 76.8 x 8.4 mm", "berat": "200 g", "material": "Plastik depan-belakang", "simDetail": "Hybrid Dual SIM + microSD s/d 1TB", "tahanAir": "-", "tambahan": "Key Island, jack 3.5mm" },
    "display": { "tipe": "Super AMOLED 90Hz", "ukuran": "6.5 inci", "resolusi": "1080 x 2340 piksel, 396 ppi", "kecerahan": "800 nits (HBM)", "proteksi": "-", "refreshRate": 90, "sizeInch": 6.5 },
    "platform": { "os": "One UI 6 Android 14 (upgrade ke Android 18)", "chipset": "Dimensity 6100+ (6 nm)", "cpu": "Octa-core (2x2.2GHz + 6x2.0GHz)", "gpu": "Mali-G57 MC2" },
    "memory": { "slotKartu": "Ya, hybrid microSD s/d 1TB", "ram": [8], "ramUtama": 8, "internal": [128, 256], "storageUtama": 128, "tipe": "UFS 2.2" },
    "mainCamera": { "konfigurasi": "50MP wide + 5MP ultrawide + 2MP macro", "detail": "50 MP, f/1.8 | 5 MP ultrawide | 2 MP macro", "fitur": "Night mode, panorama", "video": "1080p@30fps" },
    "selfieCamera": { "resolusi": "13 MP, f/2.0", "fitur": "Portrait", "video": "1080p@30fps" },
    "sound": { "pengeras": "Mono", "jack": "Ada, 3.5mm", "tambahan": "-" },
    "comms": { "wifi": "Wi-Fi ac dual-band", "bluetooth": "5.3", "nfc": true, "infrared": false, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint samping", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "25W kabel (50% 30 mnt)", "wireless": false },
    "prices": [
      { "toko": "Samsung Official Store", "harga": 3299000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Erafone", "harga": 3199000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Rp 12.000", "garansi": "Resmi 1 tahun" },
      { "toko": "Tokopedia - SelulerKu", "harga": 2999000, "stok": "Ready", "ratingToko": 4.6, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Layar AMOLED 90Hz termurah Samsung", "Ada NFC dan microSD", "Update 4+5 tahun", "Baterai 5000 mAh awet"],
    "cons": ["Charging 25W lambat", "Speaker mono", "Chipset pas untuk harian"]
  },
  {
    "id": "samsung-galaxy-s23-fe",
    "name": "Samsung Galaxy S23 FE",
    "brand": "Samsung",
    "released": "2023-10-20",
    "status": "Tersedia",
    "priceIDR": 7999000,
    "priceUSD": 599,
    "rating": 4.4,
    "reviewCount": 1180,
    "hits": 1430220,
    "antutu": 890500,
    "colors": ["Graphite", "Cream", "Mint", "Purple"],
    "colorHex": ["#3a3b3d", "#f0e9d6", "#a8d5ba", "#b9a7d6"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM + eSIM", "dukungan5G": true },
    "launch": { "diumumkan": "04 Okt 2023", "rilis": "20 Okt 2023", "status": "Tersedia" },
    "body": { "dimensi": "158 x 76.5 x 8.2 mm", "berat": "209 g", "material": "Gorilla Glass 5 depan-belakang, aluminium", "simDetail": "Dual Nano-SIM + eSIM", "tahanAir": "IP68", "tambahan": "-" },
    "display": { "tipe": "Dynamic AMOLED 2X 120Hz, HDR10+", "ukuran": "6.4 inci", "resolusi": "1080 x 2340 piksel, 403 ppi", "kecerahan": "1450 nits peak", "proteksi": "Gorilla Glass 5", "refreshRate": 120, "sizeInch": 6.4 },
    "platform": { "os": "One UI 5.1 Android 13 (upgrade ke Android 17)", "chipset": "Exynos 2200 (4 nm)", "cpu": "Octa-core (1x2.8GHz + 3x2.52GHz + 4x1.82GHz)", "gpu": "Xclipse 920" },
    "memory": { "slotKartu": "Tidak", "ram": [8], "ramUtama": 8, "internal": [128, 256], "storageUtama": 128, "tipe": "UFS 3.1" },
    "mainCamera": { "konfigurasi": "50MP wide OIS + 12MP ultrawide + 8MP tele 3x", "detail": "50 MP, f/1.8, OIS | 12 MP ultrawide | 8 MP tele 3x", "fitur": "OIS, Nightography, 3x optical", "video": "8K@24fps, 4K@60fps" },
    "selfieCamera": { "resolusi": "10 MP, f/2.4", "fitur": "HDR", "video": "4K@30fps" },
    "sound": { "pengeras": "Stereo, Dolby Atmos", "jack": "Tidak ada", "tambahan": "-" },
    "comms": { "wifi": "Wi-Fi 6E", "bluetooth": "5.3", "nfc": true, "infrared": false, "usb": "USB-C 3.2", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 4500, "tipe": "Li-Po 4500 mAh", "charging": "25W kabel, 15W wireless", "wireless": true },
    "prices": [
      { "toko": "Samsung Official Store", "harga": 7999000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Tokopedia - GadgetHub", "harga": 7499000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Shopee - CellWorld", "harga": 7299000, "stok": "3 unit", "ratingToko": 4.6, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Flagship FE: tele 3x + IP68 + wireless", "Layar Dynamic AMOLED 2X", "Harga turun jauh dari rilis", "DeX dan ekosisitem Galaxy"],
    "cons": ["Exynos 2200 boros dan panas", "Baterai 4500 mAh kecil", "Charging 25W"]
  },
  {
    "id": "xiaomi-13t",
    "name": "Xiaomi 13T",
    "brand": "Xiaomi",
    "released": "2023-10-10",
    "status": "Tersedia",
    "priceIDR": 6499000,
    "priceUSD": 499,
    "rating": 4.6,
    "reviewCount": 940,
    "hits": 1210880,
    "antutu": 898000,
    "colors": ["Black", "Alpine Blue", "Meadow Green"],
    "colorHex": ["#1b1b1d", "#4a6fa5", "#4a7a5c"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM + eSIM", "dukungan5G": true },
    "launch": { "diumumkan": "26 Sep 2023", "rilis": "10 Okt 2023", "status": "Tersedia" },
    "body": { "dimensi": "162.2 x 75.7 x 8.5 mm", "berat": "197 g", "material": "Kaca / vegan leather, aluminium", "simDetail": "Dual Nano-SIM + eSIM", "tahanAir": "IP68", "tambahan": "IR Blaster" },
    "display": { "tipe": "AMOLED CrystalRes 144Hz, Dolby Vision, HDR10+", "ukuran": "6.67 inci", "resolusi": "1220 x 2712 piksel, 446 ppi", "kecerahan": "2600 nits peak", "proteksi": "Gorilla Glass 5", "refreshRate": 144, "sizeInch": 6.67 },
    "platform": { "os": "MIUI 14 Android 13 (upgrade HyperOS)", "chipset": "Dimensity 8200 Ultra (4 nm)", "cpu": "Octa-core (1x3.1GHz + 3x3.0GHz + 4x2.0GHz)", "gpu": "Mali-G610 MC6" },
    "memory": { "slotKartu": "Tidak", "ram": [12], "ramUtama": 12, "internal": [256], "storageUtama": 256, "tipe": "UFS 3.1" },
    "mainCamera": { "konfigurasi": "50MP Leica wide OIS + 50MP Leica tele 2x + 12MP ultrawide", "detail": "50 MP Sony IMX707, OIS | 50 MP tele 2x | 12 MP ultrawide", "fitur": "Leica Authentic/Vibrant, OIS", "video": "4K@30fps, HDR10+ video" },
    "selfieCamera": { "resolusi": "20 MP", "fitur": "HDR", "video": "1080p@30fps" },
    "sound": { "pengeras": "Stereo, Dolby Atmos", "jack": "Tidak ada", "tambahan": "Hi-Res" },
    "comms": { "wifi": "Wi-Fi 6", "bluetooth": "5.4", "nfc": true, "infrared": true, "usb": "USB-C 2.0, OTG", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "67W turbo (100% 42 mnt)", "wireless": false },
    "prices": [
      { "toko": "Xiaomi Official Store", "harga": 6499000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Erafone", "harga": 6299000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Kamera Leica + lensa tele 2x langka di 6 jutaan", "IP68 + layar 144Hz 2600 nits", "Update 4 Android + 5 tahun security", "67W cepat"],
    "cons": ["Tanpa wireless charging", "Ultrawide biasa", "Video selfie 1080p"]
  },
  {
    "id": "xiaomi-redmi-13c",
    "name": "Xiaomi Redmi 13C",
    "brand": "Xiaomi",
    "released": "2023-11-20",
    "status": "Tersedia",
    "priceIDR": 1499000,
    "priceUSD": 109,
    "rating": 4.2,
    "reviewCount": 5210,
    "hits": 2340770,
    "antutu": 258400,
    "colors": ["Midnight Black", "Navy Blue", "Clover Green"],
    "colorHex": ["#1b1b1d", "#2c3e60", "#3d6b4f"],
    "network": { "teknologi": "GSM / HSPA / LTE", "sim": "Dual Nano-SIM + microSD", "dukungan5G": false },
    "launch": { "diumumkan": "10 Nov 2023", "rilis": "20 Nov 2023", "status": "Tersedia" },
    "body": { "dimensi": "168 x 78 x 8.1 mm", "berat": "192 g", "material": "Plastik", "simDetail": "Dual Nano-SIM + microSD s/d 1TB", "tahanAir": "-", "tambahan": "Jack 3.5mm, FM radio" },
    "display": { "tipe": "IPS LCD 90Hz", "ukuran": "6.74 inci", "resolusi": "720 x 1600 piksel, 260 ppi", "kecerahan": "600 nits", "proteksi": "Gorilla Glass", "refreshRate": 90, "sizeInch": 6.74 },
    "platform": { "os": "MIUI 14 Android 13", "chipset": "Helio G85 (12 nm)", "cpu": "Octa-core (2x2.0GHz + 6x1.8GHz)", "gpu": "Mali-G52 MC2" },
    "memory": { "slotKartu": "Ya, microSD s/d 1TB", "ram": [6, 8], "ramUtama": 8, "internal": [128, 256], "storageUtama": 128, "tipe": "eMMC 5.1" },
    "mainCamera": { "konfigurasi": "50MP wide + 2MP macro + QVGA", "detail": "50 MP, f/1.8 | 2 MP macro", "fitur": "Night mode, film filters", "video": "1080p@30fps" },
    "selfieCamera": { "resolusi": "8 MP, f/2.0", "fitur": "Soft light ring", "video": "1080p@30fps" },
    "sound": { "pengeras": "Mono", "jack": "Ada, 3.5mm", "tambahan": "-" },
    "comms": { "wifi": "Wi-Fi n dual-band", "bluetooth": "5.3", "nfc": true, "infrared": false, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint samping", "Accelerometer", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "18W kabel", "wireless": false },
    "prices": [
      { "toko": "Xiaomi Official Store", "harga": 1499000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Shopee - Mi Store", "harga": 1399000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Termurah dengan NFC dan 90Hz", "Baterai 5000 mAh awet 2 hari", "Ada microSD + jack", "Cocok HP kedua"],
    "cons": ["4G saja, tanpa 5G", "Layar HD+ kurang tajam", "eMMC lambat, tanpa gyro hardware"]
  },
  {
    "id": "poco-f6",
    "name": "POCO F6 5G",
    "brand": "Xiaomi",
    "released": "2024-05-27",
    "status": "Tersedia",
    "priceIDR": 5299000,
    "priceUSD": 379,
    "rating": 4.7,
    "reviewCount": 1120,
    "hits": 1650220,
    "antutu": 1520800,
    "colors": ["Black", "Green", "Titanium"],
    "colorHex": ["#1b1b1d", "#3d5a4c", "#8a8d91"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM", "dukungan5G": true },
    "launch": { "diumumkan": "23 Mei 2024", "rilis": "27 Mei 2024", "status": "Tersedia" },
    "body": { "dimensi": "160.5 x 74.4 x 7.8 mm", "berat": "179 g", "material": "Plastik, Gorilla Glass Victus depan", "simDetail": "Dual Nano-SIM", "tahanAir": "IP64", "tambahan": "IR Blaster" },
    "display": { "tipe": "AMOLED CrystalRes 120Hz, Dolby Vision", "ukuran": "6.67 inci", "resolusi": "1220 x 2712 piksel, 446 ppi", "kecerahan": "2400 nits peak", "proteksi": "Gorilla Glass Victus", "refreshRate": 120, "sizeInch": 6.67 },
    "platform": { "os": "HyperOS Android 14", "chipset": "Snapdragon 8s Gen 3 (4 nm)", "cpu": "Octa-core (1x3.0GHz + 4x2.8GHz + 3x2.0GHz)", "gpu": "Adreno 735" },
    "memory": { "slotKartu": "Tidak", "ram": [8, 12], "ramUtama": 12, "internal": [256, 512], "storageUtama": 256, "tipe": "UFS 4.0" },
    "mainCamera": { "konfigurasi": "50MP Sony IMX920 OIS + 8MP ultrawide", "detail": "50 MP IMX920, f/1.6, OIS | 8 MP ultrawide", "fitur": "OIS, Night mode, HyperOIS", "video": "4K@60fps" },
    "selfieCamera": { "resolusi": "20 MP", "fitur": "HDR", "video": "1080p@30fps" },
    "sound": { "pengeras": "Stereo, Dolby Atmos", "jack": "Tidak ada", "tambahan": "Hi-Res" },
    "comms": { "wifi": "Wi-Fi 6", "bluetooth": "5.4", "nfc": true, "infrared": true, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "90W turbo (100% 35 mnt)", "wireless": false },
    "prices": [
      { "toko": "POCO Official Store", "harga": 5299000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Shopee - POCO ID", "harga": 5099000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Snapdragon 8s Gen 3 terkencang di 5 jutaan", "Ringan 179g + 90W", "Kamera IMX920 OIS bukan ala kadar", "UFS 4.0"],
    "cons": ["Tanpa lensa tele", "IP64 saja", "Bloatware HyperOS"]
  },
  {
    "id": "infinix-hot-40-pro",
    "name": "Infinix Hot 40 Pro",
    "brand": "Infinix",
    "released": "2023-12-10",
    "status": "Tersedia",
    "priceIDR": 2199000,
    "priceUSD": 149,
    "rating": 4.4,
    "reviewCount": 4310,
    "hits": 1980330,
    "antutu": 398700,
    "colors": ["Starlit Black", "Palm Blue", "Starfall Green"],
    "colorHex": ["#1b1b1d", "#3d5a80", "#3d6b4f"],
    "network": { "teknologi": "GSM / HSPA / LTE", "sim": "Dual Nano-SIM + microSD", "dukungan5G": false },
    "launch": { "diumumkan": "05 Des 2023", "rilis": "10 Des 2023", "status": "Tersedia" },
    "body": { "dimensi": "168.6 x 76.6 x 7.9 mm", "berat": "190 g", "material": "Plastik glossy", "simDetail": "Dual Nano-SIM + microSD", "tahanAir": "IP54", "tambahan": "Jack 3.5mm, DTS audio" },
    "display": { "tipe": "IPS LCD 120Hz", "ukuran": "6.78 inci", "resolusi": "1080 x 2460 piksel, 396 ppi", "kecerahan": "800 nits", "proteksi": "-", "refreshRate": 120, "sizeInch": 6.78 },
    "platform": { "os": "XOS 13.5 Android 13", "chipset": "Helio G99 (6 nm)", "cpu": "Octa-core (2x2.2GHz + 6x2.0GHz)", "gpu": "Mali-G57 MC2" },
    "memory": { "slotKartu": "Ya, microSD", "ram": [8], "ramUtama": 8, "internal": [128, 256], "storageUtama": 128, "tipe": "UFS 2.2" },
    "mainCamera": { "konfigurasi": "108MP wide + 2MP macro", "detail": "108 MP, f/1.8 | 2 MP macro", "fitur": "Super Night, Sky Shop", "video": "1440p@30fps" },
    "selfieCamera": { "resolusi": "32 MP, f/2.2", "fitur": "Dual LED flash", "video": "1080p@30fps" },
    "sound": { "pengeras": "Stereo DTS", "jack": "Ada, 3.5mm", "tambahan": "DTS" },
    "comms": { "wifi": "Wi-Fi ac", "bluetooth": "5.0", "nfc": true, "infrared": false, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS", "uwb": false },
    "sensors": ["Fingerprint samping", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "33W kabel", "wireless": false },
    "prices": [
      { "toko": "Infinix Official Store", "harga": 2199000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Tokopedia - Infinix", "harga": 2099000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["Helio G99 + 120Hz FHD termurah", "Kamera 108MP + selfie 32MP", "Stereo + jack + NFC", "Magisk? tidak, XOS ringan"],
    "cons": ["4G saja", "Update 2 tahun", "Plastik mudah baret"]
  },
  {
    "id": "realme-c67",
    "name": "Realme C67",
    "brand": "Realme",
    "released": "2023-12-25",
    "status": "Tersedia",
    "priceIDR": 2599000,
    "priceUSD": 169,
    "rating": 4.3,
    "reviewCount": 2870,
    "hits": 1540770,
    "antutu": 312500,
    "colors": ["Sunny Oasis", "Black Rock"],
    "colorHex": ["#7fb8b5", "#1c1c1e"],
    "network": { "teknologi": "GSM / HSPA / LTE", "sim": "Dual Nano-SIM + microSD", "dukungan5G": false },
    "launch": { "diumumkan": "19 Des 2023", "rilis": "25 Des 2023", "status": "Tersedia" },
    "body": { "dimensi": "164.6 x 75.4 x 7.6 mm", "berat": "185 g", "material": "Plastik", "simDetail": "Dual Nano-SIM + microSD", "tahanAir": "IP54", "tambahan": "Mini Capsule, jack 3.5mm" },
    "display": { "tipe": "IPS LCD 90Hz", "ukuran": "6.72 inci", "resolusi": "1080 x 2400 piksel, 392 ppi", "kecerahan": "950 nits", "proteksi": "-", "refreshRate": 90, "sizeInch": 6.72 },
    "platform": { "os": "Realme UI 4.0 Android 13", "chipset": "Snapdragon 685 (6 nm)", "cpu": "Octa-core (4x2.8GHz + 4x1.9GHz)", "gpu": "Adreno 610" },
    "memory": { "slotKartu": "Ya, microSD", "ram": [8], "ramUtama": 8, "internal": [128, 256], "storageUtama": 128, "tipe": "UFS 2.2" },
    "mainCamera": { "konfigurasi": "108MP Samsung HM6 + 2MP depth", "detail": "108 MP HM6, f/1.8, 3x zoom sensor | 2 MP depth", "fitur": "3x in-sensor zoom", "video": "1080p@30fps" },
    "selfieCamera": { "resolusi": "8 MP, f/2.1", "fitur": "Portrait", "video": "1080p@30fps" },
    "sound": { "pengeras": "Mono, 150% UltraBoom", "jack": "Ada, 3.5mm", "tambahan": "-" },
    "comms": { "wifi": "Wi-Fi ac", "bluetooth": "5.0", "nfc": true, "infrared": false, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint samping", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "33W SuperVOOC", "wireless": false },
    "prices": [
      { "toko": "Realme Official Store", "harga": 2599000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Erafone", "harga": 2499000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["108MP + 3x zoom sensor di 2 jutaan", "Tipis 7.6mm ringan", "NFC + 33W + speaker 150%", "Mini Capsule ala Dynamic Island"],
    "cons": ["4G saja", "Layar IPS bukan AMOLED", "Snapdragon 685 untuk harian"]
  },
  {
    "id": "oppo-a78",
    "name": "Oppo A78",
    "brand": "Oppo",
    "released": "2023-08-05",
    "status": "Tersedia",
    "priceIDR": 3499000,
    "priceUSD": 229,
    "rating": 4.4,
    "reviewCount": 1980,
    "hits": 1210450,
    "antutu": 295800,
    "colors": ["Aqua Green", "Mist Black"],
    "colorHex": ["#5fa8a0", "#23262b"],
    "network": { "teknologi": "GSM / HSPA / LTE", "sim": "Dual Nano-SIM + microSD", "dukungan5G": false },
    "launch": { "diumumkan": "20 Jul 2023", "rilis": "05 Agu 2023", "status": "Tersedia" },
    "body": { "dimensi": "160 x 73.2 x 7.9 mm", "berat": "180 g", "material": "Plastik Diamond Matrix", "simDetail": "Dual Nano-SIM + microSD", "tahanAir": "IP54", "tambahan": "Jack 3.5mm, 300% Ultra Volume" },
    "display": { "tipe": "AMOLED 90Hz, HDR10", "ukuran": "6.43 inci", "resolusi": "1080 x 2400 piksel, 409 ppi", "kecerahan": "800 nits", "proteksi": "Gorilla Glass 5", "refreshRate": 90, "sizeInch": 6.43 },
    "platform": { "os": "ColorOS 13.1 Android 13", "chipset": "Snapdragon 680 (6 nm)", "cpu": "Octa-core (4x2.4GHz + 4x1.9GHz)", "gpu": "Adreno 610" },
    "memory": { "slotKartu": "Ya, microSD", "ram": [8], "ramUtama": 8, "internal": [128, 256], "storageUtama": 128, "tipe": "UFS 2.2" },
    "mainCamera": { "konfigurasi": "50MP wide + 2MP depth", "detail": "50 MP, f/1.8 | 2 MP depth", "fitur": "Portrait bokeh, Night", "video": "1080p@30fps" },
    "selfieCamera": { "resolusi": "8 MP, f/2.0", "fitur": "Beautify", "video": "1080p@30fps" },
    "sound": { "pengeras": "Stereo, 300% volume", "jack": "Ada, 3.5mm", "tambahan": "Ultra Volume" },
    "comms": { "wifi": "Wi-Fi ac", "bluetooth": "5.0", "nfc": true, "infrared": false, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "67W SuperVOOC (100% 45 mnt)", "wireless": false },
    "prices": [
      { "toko": "Oppo Official Store", "harga": 3499000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Tokopedia - Oppo Gallery", "harga": 3299000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["AMOLED + fingerprint layar di 3 jutaan", "67W tercepat di kelas", "Stereo 300% + jack + NFC", "Desain Diamond Matrix"],
    "cons": ["4G, Snapdragon 680 harian", "Kamera tanpa ultrawide", "Video mentok 1080p"]
  },
  {
    "id": "vivo-y36-5g",
    "name": "Vivo Y36 5G",
    "brand": "Vivo",
    "released": "2023-07-15",
    "status": "Tersedia",
    "priceIDR": 3399000,
    "priceUSD": 219,
    "rating": 4.3,
    "reviewCount": 1760,
    "hits": 1100340,
    "antutu": 385600,
    "colors": ["Crystal Green", "Mystic Black"],
    "colorHex": ["#7fb8a0", "#23262b"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM + microSD", "dukungan5G": true },
    "launch": { "diumumkan": "05 Jul 2023", "rilis": "15 Jul 2023", "status": "Tersedia" },
    "body": { "dimensi": "164.1 x 74.9 x 8.1 mm", "berat": "190 g", "material": "Plastik glossy", "simDetail": "Dual Nano-SIM + microSD", "tahanAir": "IP54", "tambahan": "Jack 3.5mm" },
    "display": { "tipe": "IPS LCD 90Hz", "ukuran": "6.64 inci", "resolusi": "1080 x 2388 piksel, 395 ppi", "kecerahan": "650 nits", "proteksi": "-", "refreshRate": 90, "sizeInch": 6.64 },
    "platform": { "os": "Funtouch 13 Android 13", "chipset": "Dimensity 6020 (7 nm)", "cpu": "Octa-core (2x2.2GHz + 6x2.0GHz)", "gpu": "Mali-G57 MC2" },
    "memory": { "slotKartu": "Ya, microSD", "ram": [8], "ramUtama": 8, "internal": [128], "storageUtama": 128, "tipe": "UFS 2.2" },
    "mainCamera": { "konfigurasi": "50MP wide + 2MP bokeh", "detail": "50 MP, f/1.8 | 2 MP bokeh", "fitur": "Night, portrait", "video": "1080p@30fps" },
    "selfieCamera": { "resolusi": "16 MP, f/2.0", "fitur": "Aura Screen Light", "video": "1080p@30fps" },
    "sound": { "pengeras": "Mono", "jack": "Ada, 3.5mm", "tambahan": "150% volume" },
    "comms": { "wifi": "Wi-Fi ac", "bluetooth": "5.1", "nfc": true, "infrared": false, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint samping", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "44W FlashCharge", "wireless": false },
    "prices": [
      { "toko": "Vivo Official Store", "harga": 3399000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" },
      { "toko": "Erafone", "harga": 3299000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi 1 tahun" }
    ],
    "pros": ["5G + NFC + 44W di 3 jutaan", "Desain tipis glossy", "Ada microSD + jack", "Funtouch stabil"],
    "cons": ["Layar IPS bukan AMOLED", "Kamera tanpa ultrawide", "Speaker mono"]
  },
  {
    "id": "iphone-13",
    "name": "Apple iPhone 13",
    "brand": "Apple",
    "released": "2021-09-24",
    "status": "Tersedia",
    "priceIDR": 9499000,
    "priceUSD": 599,
    "rating": 4.7,
    "reviewCount": 4210,
    "hits": 3120550,
    "antutu": 912400,
    "colors": ["Midnight", "Starlight", "Blue", "Pink", "Green"],
    "colorHex": ["#23262b", "#e8e0d5", "#4a6fa5", "#e8a7b8", "#5a7a5c"],
    "network": { "teknologi": "GSM / CDMA / HSPA / EVDO / LTE / 5G", "sim": "Nano-SIM + eSIM", "dukungan5G": true },
    "launch": { "diumumkan": "14 Sep 2021", "rilis": "24 Sep 2021", "status": "Tersedia" },
    "body": { "dimensi": "146.7 x 71.5 x 7.7 mm", "berat": "174 g", "material": "Aluminium, Ceramic Shield depan", "simDetail": "Nano-SIM + eSIM", "tahanAir": "IP68 (6m, 30 mnt)", "tambahan": "Face ID, MagSafe" },
    "display": { "tipe": "Super Retina XDR OLED, HDR10, Dolby Vision", "ukuran": "6.1 inci", "resolusi": "1170 x 2532 piksel, 460 ppi", "kecerahan": "1200 nits peak", "proteksi": "Ceramic Shield", "refreshRate": 60, "sizeInch": 6.1 },
    "platform": { "os": "iOS 15 (upgrade ke iOS 18)", "chipset": "Apple A15 Bionic (5 nm)", "cpu": "Hexa-core (2x3.23GHz + 4x1.82GHz)", "gpu": "Apple GPU 4-core" },
    "memory": { "slotKartu": "Tidak", "ram": [4], "ramUtama": 4, "internal": [128, 256, 512], "storageUtama": 128, "tipe": "NVMe" },
    "mainCamera": { "konfigurasi": "12MP wide sensor-shift + 12MP ultrawide", "detail": "12 MP, f/1.6, sensor-shift OIS | 12 MP ultrawide", "fitur": "Night mode, Photographic Styles, Cinematic", "video": "4K@60fps, Dolby Vision HDR" },
    "selfieCamera": { "resolusi": "12 MP, f/2.2 + SL 3D", "fitur": "Face ID, Night mode", "video": "4K@60fps" },
    "sound": { "pengeras": "Stereo, Dolby Atmos", "jack": "Tidak ada", "tambahan": "Spatial Audio" },
    "comms": { "wifi": "Wi-Fi 6", "bluetooth": "5.0", "nfc": true, "infrared": false, "usb": "Lightning, USB 2.0", "gps": "GPS, GLONASS, GALILEO, QZSS, BeiDou", "uwb": true },
    "sensors": ["Face ID", "Accelerometer", "Gyro", "Proximity", "Kompas", "Barometer"],
    "battery": { "kapasitas": 3240, "tipe": "Li-Ion 3240 mAh", "charging": "20W kabel (50% 30 mnt), 15W MagSafe", "wireless": true },
    "prices": [
      { "toko": "iBox Official", "harga": 9499000, "stok": "Ready", "ratingToko": 4.9, "ongkir": "Gratis", "garansi": "Resmi Apple 1 tahun" },
      { "toko": "Digimap", "harga": 9299000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Resmi Apple 1 tahun" },
      { "toko": "Tokopedia - iStyle", "harga": 8999000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Resmi Apple 1 tahun" }
    ],
    "pros": ["iPhone termurah yang masih sangat relevan", "A15 + kamera sensor-shift stabil", "Compact 174g, Face ID cepat", "Update iOS 6 tahun"],
    "cons": ["Layar 60Hz tertinggal", "Lightning bukan USB-C", "Charging 20W lambat"]
  },
  {
    "id": "google-pixel-7a",
    "name": "Google Pixel 7a",
    "brand": "Google",
    "released": "2023-05-11",
    "status": "Tersedia",
    "priceIDR": 7499000,
    "priceUSD": 499,
    "rating": 4.5,
    "reviewCount": 720,
    "hits": 980220,
    "antutu": 768300,
    "colors": ["Charcoal", "Snow", "Sea"],
    "colorHex": ["#23262b", "#e8e8e6", "#9fc3e0"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Nano-SIM + eSIM", "dukungan5G": true },
    "launch": { "diumumkan": "10 Mei 2023", "rilis": "11 Mei 2023", "status": "Tersedia" },
    "body": { "dimensi": "152.4 x 72.9 x 9 mm", "berat": "193.5 g", "material": "Plastik belakang, aluminium, Gorilla Glass 3", "simDetail": "Nano-SIM + eSIM", "tahanAir": "IP67", "tambahan": "-" },
    "display": { "tipe": "OLED 90Hz, HDR", "ukuran": "6.1 inci", "resolusi": "1080 x 2400 piksel, 429 ppi", "kecerahan": "1000 nits", "proteksi": "Gorilla Glass 3", "refreshRate": 90, "sizeInch": 6.1 },
    "platform": { "os": "Android 13 (update 5 tahun)", "chipset": "Google Tensor G2 (5 nm)", "cpu": "Octa-core (2x2.85GHz + 2x2.35GHz + 4x1.80GHz)", "gpu": "Mali-G710 MP7" },
    "memory": { "slotKartu": "Tidak", "ram": [8], "ramUtama": 8, "internal": [128], "storageUtama": 128, "tipe": "UFS 3.1" },
    "mainCamera": { "konfigurasi": "64MP wide OIS + 13MP ultrawide", "detail": "64 MP, f/1.9, OIS | 13 MP ultrawide", "fitur": "Magic Eraser, Night Sight, Long Exposure", "video": "4K@60fps, OIS" },
    "selfieCamera": { "resolusi": "13 MP, f/2.2", "fitur": "Auto HDR", "video": "4K@30fps" },
    "sound": { "pengeras": "Stereo", "jack": "Tidak ada", "tambahan": "-" },
    "comms": { "wifi": "Wi-Fi 6E", "bluetooth": "5.3", "nfc": true, "infrared": false, "usb": "USB-C 3.2", "gps": "GPS, GLONASS, BDS, GALILEO, QZSS", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas", "Barometer"],
    "battery": { "kapasitas": 4385, "tipe": "Li-Po 4385 mAh", "charging": "18W kabel, 7.5W wireless", "wireless": true },
    "prices": [
      { "toko": "Google Store Partner", "harga": 7499000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Distributor 1 tahun" },
      { "toko": "Tokopedia - PixelID", "harga": 7199000, "stok": "Ready", "ratingToko": 4.6, "ongkir": "Gratis", "garansi": "Distributor 1 tahun" }
    ],
    "pros": ["Kamera Pixel + IP67 termurah", "Compact 6.1 inci", "Update 5 tahun + AI Magic Eraser", "Wireless charging ada"],
    "cons": ["Charging 18W lambat", "Bezel tebal", "Tensor G2 hangat"]
  },
  {
    "id": "oneplus-nord-3",
    "name": "OnePlus Nord 3 5G",
    "brand": "OnePlus",
    "released": "2023-07-15",
    "status": "Tersedia",
    "priceIDR": 5999000,
    "priceUSD": 449,
    "rating": 4.5,
    "reviewCount": 480,
    "hits": 760310,
    "antutu": 1052400,
    "colors": ["Tempest Gray", "Misty Green"],
    "colorHex": ["#4a4d52", "#7fa8a0"],
    "network": { "teknologi": "GSM / HSPA / LTE / 5G", "sim": "Dual Nano-SIM", "dukungan5G": true },
    "launch": { "diumumkan": "05 Jul 2023", "rilis": "15 Jul 2023", "status": "Tersedia" },
    "body": { "dimensi": "162.6 x 75.1 x 8.2 mm", "berat": "193.5 g", "material": "Gorilla Glass 5 depan, plastik belakang", "simDetail": "Dual Nano-SIM", "tahanAir": "IP54", "tambahan": "Alert Slider, IR Blaster" },
    "display": { "tipe": "AMOLED 120Hz, HDR10+", "ukuran": "6.74 inci", "resolusi": "1240 x 2772 piksel, 450 ppi", "kecerahan": "1450 nits", "proteksi": "Dragontrail Glass", "refreshRate": 120, "sizeInch": 6.74 },
    "platform": { "os": "OxygenOS 13.1 Android 13", "chipset": "Dimensity 9000 (4 nm)", "cpu": "Octa-core (1x3.05GHz + 3x2.85GHz + 4x1.80GHz)", "gpu": "Mali-G710 MC10" },
    "memory": { "slotKartu": "Tidak", "ram": [8, 16], "ramUtama": 16, "internal": [128, 256], "storageUtama": 128, "tipe": "UFS 3.1" },
    "mainCamera": { "konfigurasi": "50MP Sony IMX890 OIS + 8MP ultrawide + 2MP macro", "detail": "50 MP IMX890, f/1.9, OIS | 8 MP ultrawide", "fitur": "OIS, Nightscape, TurboRAW", "video": "4K@60fps" },
    "selfieCamera": { "resolusi": "16 MP, f/2.4", "fitur": "Auto HDR", "video": "1080p@30fps" },
    "sound": { "pengeras": "Stereo, Dolby Atmos", "jack": "Tidak ada", "tambahan": "Hi-Res" },
    "comms": { "wifi": "Wi-Fi 6", "bluetooth": "5.3", "nfc": true, "infrared": true, "usb": "USB-C 2.0", "gps": "GPS, GLONASS, BDS, GALILEO", "uwb": false },
    "sensors": ["Fingerprint di layar", "Accelerometer", "Gyro", "Proximity", "Kompas"],
    "battery": { "kapasitas": 5000, "tipe": "Li-Po 5000 mAh", "charging": "80W SuperVOOC (100% 32 mnt)", "wireless": false },
    "prices": [
      { "toko": "OnePlus Official", "harga": 5999000, "stok": "Ready", "ratingToko": 4.8, "ongkir": "Gratis", "garansi": "Distributor 1 tahun" },
      { "toko": "Tokopedia - OnePlus ID", "harga": 5799000, "stok": "Ready", "ratingToko": 4.7, "ongkir": "Gratis", "garansi": "Distributor 1 tahun" }
    ],
    "pros": ["Dimensity 9000 + RAM 16GB di 6 jutaan", "Kamera IMX890 OIS flagship", "80W + Alert Slider", "OxygenOS bersih"],
    "cons": ["IP54 saja", "Plastik belakang", "Tidak resmi Indonesia"]
  }
];

const NEWS = [
  { "id": 1, "judul": "Samsung Galaxy S25 Ultra bocor: Snapdragon 8 Elite, kamera 200MP baru", "kategori": "Rumor", "tanggal": "2026-09-28", "ringkasan": "Render CAD mengungkap sudut membulat, bezel 0.8mm, dan RAM 16GB untuk pertama kalinya di seri Ultra.", "isi": "Berdasarkan dokumen sertifikasi dan render OnLeaks, Galaxy S25 Ultra akan memakai Snapdragon 8 Elite for Galaxy, layar 6.9 inci QHD+ 3000 nits, dan kamera ultrawide 50MP baru. Baterai tetap 5000 mAh dengan charging 45W. Peluncuran diprediksi Januari 2026 dengan harga mulai Rp 22,9 juta.", "terkait": ["samsung-galaxy-s24-ultra", "oneplus-12"] },
  { "id": 2, "judul": "POCO X6 Pro vs Redmi Note 13 Pro: mana yang layak dibeli 2026?", "kategori": "Komparasi", "tanggal": "2026-09-20", "ringkasan": "Selisih Rp 500 ribu, beda kelas performa. Kami uji gaming, kamera, dan baterai keduanya.", "isi": "POCO X6 Pro unggul jauh di performa (Dimensity 8300 Ultra, AnTuTu 1,4 juta vs 608 ribu) dan cocok untuk gaming. Redmi Note 13 Pro 5G menang di kamera 200MP dengan OIS lebih stabil dan layar dengan bezel lebih tipis. Jika prioritas gaming pilih POCO, jika kamera dan desain pilih Redmi.", "terkait": ["poco-x6-pro", "xiaomi-redmi-note-13-pro"] },
  { "id": 3, "judul": "Infinix Note 40 Pro 5G resmi: HP 3 jutaan pertama dengan wireless charging", "kategori": "Peluncuran", "tanggal": "2026-09-12", "ringkasan": "70W kabel + 20W wireless MagCharge, layar AMOLED curved 120Hz, speaker JBL.", "isi": "Infinix Note 40 Pro 5G resmi masuk Indonesia Rp 3.499.000 (8/256GB). Keunggulannya adalah wireless charging 20W magnetik pertama di harga 3 jutaan, layar curved 6.78 inci AMOLED, dan kamera 108MP OIS. Paket penjualan termasuk MagPad dan MagCase.", "terkait": ["infinix-note-40-pro", "infinix-hot-40-pro"] },
  { "id": 4, "judul": "Tips: cara cek HP second agar tidak tertipu refurbish", "kategori": "Tips", "tanggal": "2026-09-05", "ringkasan": "Cek IMEI, sensor, baterai health, dan segel baut sebelum bayar.", "isi": "1) Cek IMEI di kemenperin.go.id. 2) Tes semua sensor via kode *#0*# (Samsung) atau aplikasi Phone Doctor. 3) Cek battery health di atas 85 persen. 4) Periksa segel baut dan bekas lem LCD. 5) Lakukan reset pabrik di tempat dan login ulang akun.", "terkait": ["samsung-galaxy-a15-5g", "xiaomi-redmi-13c", "iphone-13"] },
  { "id": 5, "judul": "HP 2 jutaan terbaik 2026: NFC wajib, refresh rate minimal 90Hz", "kategori": "Panduan", "tanggal": "2026-08-28", "ringkasan": "Dari 7 tipe 1-3 jutaan di database, hanya 5 yang punya NFC dan layar Full HD.", "isi": "Untuk budget 2 jutaan, prioritaskan NFC (e-money dan e-KTP), layar minimal FHD 90Hz, dan charging 33W. Infinix Hot 40 Pro menang performa (Helio G99 + 120Hz), Realme C67 menang kamera (108MP 3x zoom), Oppo A78 menang layar (AMOLED + fingerprint di layar). Hindari yang masih eMMC dan tanpa gyro hardware jika suka gaming.", "terkait": ["infinix-hot-40-pro", "realme-c67", "oppo-a78"] },
  { "id": 6, "judul": "POCO F6 vs Xiaomi 13T: beda Rp 1,2 juta, pilih gaming atau kamera Leica?", "kategori": "Komparasi", "tanggal": "2026-08-18", "ringkasan": "Snapdragon 8s Gen 3 vs Dimensity 8200 Ultra, IMX920 vs Leica IMX707.", "isi": "POCO F6 (Rp 5,2 juta) unggul AnTuTu 1,52 juta vs 898 ribu, lebih ringan, charging 90W. Xiaomi 13T (Rp 6,4 juta) unggul kamera Leica + tele 2x, IP68, layar 144Hz 2600 nits. Gamer murni pilih F6. Fotografer pilih 13T. Keduanya dapat update panjang dan NFC.", "terkait": ["poco-f6", "xiaomi-13t"] },
  { "id": 7, "judul": "iPhone 13 di 2026: masih layak dibeli di bawah Rp 9 juta?", "kategori": "Analisis", "tanggal": "2026-08-08", "ringkasan": "A15 masih kencang, tapi layar 60Hz dan Lightning jadi catatan.", "isi": "iPhone 13 bekas resmi kini Rp 8,9 juta. Kelebihan: compact, Face ID, update sampai iOS 18, video sinematik. Kekurangan: 60Hz vs Android 90-120Hz di harga sama, Lightning, baterai 3240 mAh. Layak jika butuh iOS murah dan compact. Jika prioritas layar dan baterai, Galaxy S23 FE atau Xiaomi 13T lebih masuk akal.", "terkait": ["iphone-13", "samsung-galaxy-s23-fe", "xiaomi-13t"] },
  { "id": 8, "judul": "Arti IP rating: IP54 vs IP67 vs IP68 untuk pemakaian harian", "kategori": "Tips", "tanggal": "2026-07-30", "ringkasan": "IP54 hanya cipratan, IP67 rendaman dangkal, IP68 rendaman dalam.", "isi": "IP54 (Redmi Note 13 Pro, Reno 11 Pro): tahan cipratan hujan, bukan rendaman. IP67 (Galaxy A54, Pixel 7a): rendaman 1m 30 menit. IP68 (S24 Ultra, iPhone, Xiaomi 13T): rendaman lebih dalam dan debu penuh. Jangan sengaja rendam HP walau IP68 karena garansi tidak mencakup cairan. Untuk ojek dan hujan Jakarta, minimal IP54, ideal IP67 ke atas.", "terkait": ["samsung-galaxy-a54", "google-pixel-7a", "xiaomi-13t"] }
];

module.exports = { PHONES, NEWS };
